/-
Copyright (c) 2026 Benjamin Brast-McKie. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Benjamin Brast-McKie
-/

module

import Mathlib.Tactic.Ring
public import Cslib.Logics.Modal.Tableau.FmpMeasure
public import Cslib.Logics.Modal.Tableau.LoopChecking

/-! # S5 Universal-Cluster Tableau Simplification

This module defines the S5 "propagate box to ALL branch worlds" universal rule
(`modalApplyOneS5`), which realises S5's single-cluster model property directly, without any
loop-checking machinery (unlike S4, `LoopChecking.lean`). It instantiates the generic tableau
driver (`Saturation.lean`'s `modalStepBranchGen`/`modalExpandBranchesGen`/`modalTableauGen`) at
`modalApplyOneS5`, mirroring the B-system build (`FrameRules.lean`/`BDriver.lean`, task 505)
declaration-for-declaration.

## Main Definitions

- `modalS5BoxAll`/`modalS5DiaNegAll`: the two universal-propagation helpers. From `T(□φ)@w`,
  emit `T(φ)@w'` for **every** known world `w'` of the branch (not just `w` itself, unlike T's
  self-propagation; not just recorded predecessors, unlike B's backward propagation), filtered
  to exclude formulas already present. Dually for `F(◇φ)@w`.
- `modalApplyOneS5`: apply the K rules (`modalApplyOne`) together with the S5 universal
  propagation arms, merging persistent-rule outputs. Reduces to `modalApplyOne` exactly outside
  the two S5-relevant signed-formula shapes (`T(□φ)@w`, `F(◇φ)@w`).
- `modalStepBranchS5`/`modalExpandBranchesS5`/`modalTableauS5`: the S5-system analogues of
  `modalStepBranch`/`modalExpandBranches`/`modalTableau`, each the generic driver instantiated
  at `apply := modalApplyOneS5`.

## Strategy

`modalApplyOneS5` agrees with `modalApplyOne` (K) outside the two S5-relevant signed-formula
shapes (`modalApplyOneS5_eq_of_not_boxPos_diaNeg`), so every `RuleApplicationSpec` field's "not
shaped" case reduces directly to the corresponding K witness. For the two S5-relevant shapes,
`modalApplyOneS5` never mints a world (its accessibility output is exactly K's, unchanged) and
only ever appends universally-propagated formulas at **existing known worlds** of the branch --
this is structurally *simpler* than B's predecessor-restricted backward propagation, since the
target-world bound follows directly from `modalKnownWorlds b`'s own bound (`label_le_modalMaxWorld`)
with no `accFreshInv`/edge-tracing detour, and the known-worlds membership (F6) is immediate by
construction (the propagation is generated by iterating over `modalKnownWorlds b` itself).

## References

* [M. Fitting, *Proof Methods for Modal and Intuitionistic Logics*][Fitting1983], Chapter 2
-/

@[expose] public section

namespace Cslib.Logic.Modal.Tableau

open Cslib.Logic.Tableau Cslib.Logic.Modal

variable {Atom : Type*} [DecidableEq Atom] [Hashable Atom]

/-! ## S5 World Bound and Universe (task 515 Phase 1)

`modalWorldBound`/`modalUniverse` (`FmpMeasure.lean`) are a branching^depth *tree* bound: S5's
universal-cluster world graph is not a bounded-depth tree (the universal rule re-broadcasts
across the whole known-world set, `S5Simplification.lean`'s module docstring), so this bound
does not transfer, exactly as it does not transfer to S4 (`LoopChecking.lean`'s `modalWorldBoundS4`
correction). `modalWorldBoundS5`/`modalUniverseS5` mirror `modalWorldBoundS4`/`modalUniverseS4`
(`LoopChecking.lean:229/235/245`) verbatim: the pigeonhole bound `2 ^ (2 * |modalSubfmls φ₀|)`,
the number of possible signed-relevant-formula sets a birth-key loop-checking argument
(`S5LoopInv`, Phase 3) can inject into. -/

/-- The S5 world bound: `2 ^ (2 * |modalSubfmls φ₀|)`, the number of possible
signed-relevant-formula sets, mirroring `modalWorldBoundS4` (`LoopChecking.lean:229`). -/
def modalWorldBoundS5 (φ₀ : Proposition Atom) : Nat :=
  2 ^ (2 * (modalSubfmls φ₀).length)

/-- The fixed finite signed-formula universe `U_{S5}(φ₀)`: both signs, every subformula of
`φ₀`, at every world label `0 .. modalWorldBoundS5 φ₀`. Mirrors `modalUniverseS4`
(`LoopChecking.lean:235`) with `modalWorldBoundS5` swapped in for `modalWorldBoundS4`. -/
def modalUniverseS5 (φ₀ : Proposition Atom) :
    List (SignedFormula (Proposition Atom) WorldIndex) :=
  (List.range (modalWorldBoundS5 φ₀ + 1)).flatMap (fun w =>
    (modalSubfmls φ₀).flatMap (fun ψ => [⟨.pos, ψ, w⟩, ⟨.neg, ψ, w⟩]))

/-- The S5 universe has length at most
`2 * (2 * modalComplexity φ₀ + 1) * (modalWorldBoundS5 φ₀ + 1)`. Mirrors
`modalUniverseS4_length_le` (`LoopChecking.lean:245`) verbatim, `S4` swapped for `S5`. -/
lemma modalUniverseS5_length_le (φ₀ : Proposition Atom) :
    (modalUniverseS5 φ₀).length ≤
      2 * (2 * modalComplexity φ₀ + 1) * (modalWorldBoundS5 φ₀ + 1) := by
  have hinner : ∀ w : WorldIndex,
      ((modalSubfmls φ₀).flatMap
        (fun ψ => [(⟨.pos, ψ, w⟩ : SignedFormula (Proposition Atom) WorldIndex),
                    ⟨.neg, ψ, w⟩])).length
        ≤ 2 * (2 * modalComplexity φ₀ + 1) := by
    intro w
    rw [List.length_flatMap]
    have hb : (List.map (fun ψ =>
        ([(⟨.pos, ψ, w⟩ : SignedFormula (Proposition Atom) WorldIndex), ⟨.neg, ψ, w⟩]).length)
        (modalSubfmls φ₀)).sum ≤ (modalSubfmls φ₀).length * 2 :=
      sum_map_le_length_mul (modalSubfmls φ₀) _ 2 (fun ψ _ => by simp)
    have hlen := modalSubfmls_length_le φ₀
    omega
  unfold modalUniverseS5
  rw [List.length_flatMap]
  have houter : (List.map (fun w =>
      ((modalSubfmls φ₀).flatMap
        (fun ψ => [(⟨.pos, ψ, w⟩ : SignedFormula (Proposition Atom) WorldIndex),
                    ⟨.neg, ψ, w⟩])).length) (List.range (modalWorldBoundS5 φ₀ + 1))).sum
      ≤ (List.range (modalWorldBoundS5 φ₀ + 1)).length * (2 * (2 * modalComplexity φ₀ + 1)) :=
    sum_map_le_length_mul (List.range (modalWorldBoundS5 φ₀ + 1)) _
      (2 * (2 * modalComplexity φ₀ + 1)) (fun w _ => hinner w)
  rw [List.length_range] at houter
  calc (List.map (fun w =>
        ((modalSubfmls φ₀).flatMap
          (fun ψ => [(⟨.pos, ψ, w⟩ : SignedFormula (Proposition Atom) WorldIndex),
                      ⟨.neg, ψ, w⟩])).length) (List.range (modalWorldBoundS5 φ₀ + 1))).sum
      ≤ (modalWorldBoundS5 φ₀ + 1) * (2 * (2 * modalComplexity φ₀ + 1)) := houter
    _ = 2 * (2 * modalComplexity φ₀ + 1) * (modalWorldBoundS5 φ₀ + 1) := by ring

/-! ## S5-Specific (Universal-Cluster) Propagation Helpers -/

/-- The S5 universal propagation for box-positives: from `T(□φ)@w`, generate `T(φ)@w'` for
**every** known world `w'` of the branch (drawn from `modalKnownWorlds b`, regardless of any
recorded edge to/from `w`), filtered to exclude formulas already present on the branch. This is
the "propagate box to ALL branch worlds" universal rule realising S5's single-cluster model
property (the extracted model's accessibility relation, taken as the `Relation.EqvGen`-closure
of recorded edges, then trivially relates every known world to every other). The trigger world
`_w` is unused (kept only for signature parity with the T/B propagation helpers, whose analogous
helpers do consult the trigger world); the universal rule propagates unconditionally. -/
@[nolint unusedArguments]
def modalS5BoxAll (b : List (SignedFormula (Proposition Atom) WorldIndex))
    (φ : Proposition Atom) (_w : WorldIndex) :
    List (SignedFormula (Proposition Atom) WorldIndex) :=
  (modalKnownWorlds b).filterMap fun w' =>
    let sf : SignedFormula (Proposition Atom) WorldIndex := ⟨.pos, φ, w'⟩
    if b.any (· == sf) then none else some sf

/-- The S5 universal propagation for diamond-negatives: from `F(◇φ)@w`, generate `F(φ)@w'` for
**every** known world `w'` of the branch, filtered to exclude formulas already present on the
branch. Dual of `modalS5BoxAll`; the trigger world `_w` is likewise unused. -/
@[nolint unusedArguments]
def modalS5DiaNegAll (b : List (SignedFormula (Proposition Atom) WorldIndex))
    (φ : Proposition Atom) (_w : WorldIndex) :
    List (SignedFormula (Proposition Atom) WorldIndex) :=
  (modalKnownWorlds b).filterMap fun w' =>
    let sf : SignedFormula (Proposition Atom) WorldIndex := ⟨.neg, φ, w'⟩
    if b.any (· == sf) then none else some sf

omit [Hashable Atom] in
/-- Membership dichotomy for `modalS5BoxAll`: every emitted formula `⟨.pos, φ, w'⟩` has `w'` a
known world of `b` and was not already on `b`. -/
lemma modalS5BoxAll_mem {b : List (SignedFormula (Proposition Atom) WorldIndex)}
    {φ : Proposition Atom} {w : WorldIndex}
    {x : SignedFormula (Proposition Atom) WorldIndex} (h : x ∈ modalS5BoxAll b φ w) :
    x = (⟨.pos, φ, x.label⟩ : SignedFormula (Proposition Atom) WorldIndex) ∧
      x.label ∈ modalKnownWorlds b ∧ x ∉ b := by
  unfold modalS5BoxAll at h
  obtain ⟨v, hv, heq⟩ := List.mem_filterMap.mp h
  dsimp only at heq
  by_cases hmem : (b.any (· == (⟨.pos, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex))) =
      true
  · rw [if_pos hmem] at heq; exact absurd heq (by simp)
  · rw [if_neg hmem] at heq
    obtain rfl : (⟨.pos, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex) = x := by
      injection heq
    exact ⟨rfl, hv, by simpa using hmem⟩

omit [Hashable Atom] in
/-- Membership dichotomy for `modalS5DiaNegAll`, dual of `modalS5BoxAll_mem`. -/
lemma modalS5DiaNegAll_mem {b : List (SignedFormula (Proposition Atom) WorldIndex)}
    {φ : Proposition Atom} {w : WorldIndex}
    {x : SignedFormula (Proposition Atom) WorldIndex} (h : x ∈ modalS5DiaNegAll b φ w) :
    x = (⟨.neg, φ, x.label⟩ : SignedFormula (Proposition Atom) WorldIndex) ∧
      x.label ∈ modalKnownWorlds b ∧ x ∉ b := by
  unfold modalS5DiaNegAll at h
  obtain ⟨v, hv, heq⟩ := List.mem_filterMap.mp h
  dsimp only at heq
  by_cases hmem : (b.any (· == (⟨.neg, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex))) =
      true
  · rw [if_pos hmem] at heq; exact absurd heq (by simp)
  · rw [if_neg hmem] at heq
    obtain rfl : (⟨.neg, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex) = x := by
      injection heq
    exact ⟨rfl, hv, by simpa using hmem⟩

omit [Hashable Atom] in
/-- Introduction direction for `modalS5BoxAll`, converse of `modalS5BoxAll_mem`: a known world
`v` of `b` not already carrying `T(φ)@v` on `b` witnesses `T(φ)@v ∈ modalS5BoxAll b φ w`. -/
lemma modalS5BoxAll_mem_of {b : List (SignedFormula (Proposition Atom) WorldIndex)}
    {φ : Proposition Atom} {w v : WorldIndex}
    (hknown : v ∈ modalKnownWorlds b)
    (hnotin : (⟨.pos, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex) ∉ b) :
    (⟨.pos, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex) ∈ modalS5BoxAll b φ w := by
  simp only [modalS5BoxAll, List.mem_filterMap]
  exact ⟨v, hknown, by rw [if_neg (by simpa using hnotin)]⟩

omit [Hashable Atom] in
/-- Introduction direction for `modalS5DiaNegAll`, dual of `modalS5BoxAll_mem_of`. -/
lemma modalS5DiaNegAll_mem_of {b : List (SignedFormula (Proposition Atom) WorldIndex)}
    {φ : Proposition Atom} {w v : WorldIndex}
    (hknown : v ∈ modalKnownWorlds b)
    (hnotin : (⟨.neg, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex) ∉ b) :
    (⟨.neg, φ, v⟩ : SignedFormula (Proposition Atom) WorldIndex) ∈ modalS5DiaNegAll b φ w := by
  simp only [modalS5DiaNegAll, List.mem_filterMap]
  exact ⟨v, hknown, by rw [if_neg (by simpa using hnotin)]⟩

/-! ## S5-Augmented Rule Application -/

/-- Apply the K modal rules together with the S5 universal-propagation arms. For the two
S5-relevant shapes (`T(□φ)@w`, `F(◇φ)@w`), the universal-propagation formulas are merged into
the K rule's `persistent` output (deduplicated); for every other signed-formula shape,
`modalApplyOneS5` reduces to exactly `modalApplyOne` (the K rule dispatch): the S5 arms are pure
`persistent` outputs at existing (known) worlds, never `linear`/`branching`, matching the
report's "no new worlds" classification for S5's universal-cluster simplification. -/
def modalApplyOneS5
    (sf : SignedFormula (Proposition Atom) WorldIndex)
    (b : List (SignedFormula (Proposition Atom) WorldIndex))
    (acc : Accessibility) :
    RuleResult (Proposition Atom) WorldIndex × Accessibility :=
  let (kResult, kAcc) := modalApplyOne sf b acc
  match sf.sign, sf.formula with
  | .pos, .box φ =>
    let allNew := modalS5BoxAll b φ sf.label
    match kResult with
    | .persistent kForms =>
      (.persistent (kForms ++ allNew.filter (fun x => !(kForms.any (· == x)))), kAcc)
    | .notApplicable =>
      if allNew.isEmpty then (.notApplicable, kAcc) else (.persistent allNew, kAcc)
    | other => (other, kAcc)
  | .neg, .diamond φ =>
    let allNew := modalS5DiaNegAll b φ sf.label
    match kResult with
    | .persistent kForms =>
      (.persistent (kForms ++ allNew.filter (fun x => !(kForms.any (· == x)))), kAcc)
    | .notApplicable =>
      if allNew.isEmpty then (.notApplicable, kAcc) else (.persistent allNew, kAcc)
    | other => (other, kAcc)
  | _, _ => (kResult, kAcc)

omit [Hashable Atom] in
/-- `modalApplyOneS5` agrees with `modalApplyOne` outside the two S5-relevant shapes
(`T(□φ)@w`, `F(◇φ)@w`): the S5 arms never affect any other rule dispatch. -/
lemma modalApplyOneS5_eq_of_not_boxPos_diaNeg
    (sf : SignedFormula (Proposition Atom) WorldIndex)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (h : ¬ (sf.sign = .pos ∧ ∃ φ, sf.formula = .box φ) ∧
         ¬ (sf.sign = .neg ∧ ∃ φ, sf.formula = .diamond φ)) :
    modalApplyOneS5 sf b acc = modalApplyOne sf b acc := by
  obtain ⟨h1, h2⟩ := h
  unfold modalApplyOneS5
  rcases hs : sf.sign with _ | _ <;> rcases hf : sf.formula with _ | _ | _ | _ | _ | φ | φ <;>
    simp_all

omit [Hashable Atom] in
/-- `modalApplyOneS5`'s accessibility output is unconditionally identical to K's
`modalApplyOne`: every match arm of `modalApplyOneS5` returns `kAcc` (the `Accessibility`
component of `modalApplyOne sf b acc`) unchanged, regardless of which `RuleResult` case is
merged into the `fst` component. This is the fact Phase 4's `accFresh`/`accKnown`
preservation lemmas need to reduce `modalApplyOneS5`'s accessibility reasoning to K's
per-call lemma (`modalApplyOne_knownWorlds_step`) uniformly, without case-splitting on
whether `sf` is one of the two S5-relevant shapes. -/
lemma modalApplyOneS5_snd_eq
    (sf : SignedFormula (Proposition Atom) WorldIndex)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility) :
    (modalApplyOneS5 sf b acc).snd = (modalApplyOne sf b acc).snd := by
  unfold modalApplyOneS5
  rcases hs : sf.sign with _ | _ <;> rcases hf : sf.formula with _ | _ | _ | _ | _ | φ | φ <;>
    simp_all <;>
    rcases h1 : (modalApplyOne sf b acc).1 with _ | _ | _ | _ <;> simp <;> split <;> simp

omit [Hashable Atom] in
/-- If K's own rule application yields a `.linear` result, `modalApplyOneS5` reduces to
`modalApplyOne` exactly (not just its accessibility component): every `modalApplyOneS5` match
arm for the two S5-relevant shapes (`sf.sign = .pos ∧ sf.formula = .box _`,
`sf.sign = .neg ∧ sf.formula = .diamond _`) falls through the `other => (other, kAcc)` default
whenever `kResult` is not `.persistent`/`.notApplicable`, and every other shape is
definitionally `(kResult, kAcc)` unconditionally. Since the two K-minting shapes
(`F(□φ)@w`/`T(◇φ)@w`) always produce a `.linear` result, this is the fact Phase 4's
`accFresh`/`accKnown` preservation lemmas need to identify `modalStepBranchS5gKeyed`'s
mint-case `(modalApplyOneS5 sf b acc).fst` with K's own per-call mint witness
(`modalApplyOne_knownWorlds_step`'s mint disjunct), without knowing `sf`'s shape statically. -/
lemma modalApplyOneS5_eq_of_linear
    (sf : SignedFormula (Proposition Atom) WorldIndex)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (nf : List (SignedFormula (Proposition Atom) WorldIndex))
    (h : (modalApplyOne sf b acc).fst = RuleResult.linear nf) :
    modalApplyOneS5 sf b acc = modalApplyOne sf b acc := by
  unfold modalApplyOneS5
  rcases hp : modalApplyOne sf b acc with ⟨kResult, kAcc⟩
  rw [hp] at h
  simp only [] at h
  subst h
  rcases hs : sf.sign with _ | _ <;> rcases hf : sf.formula with _ | _ | _ | _ | _ | φ | φ <;>
    simp_all

omit [Hashable Atom] in
/-- The expanded-set-growth shape (`e ++ [sf]` for `.linear`/`.branching`, `e` unchanged for
`.persistent`/`.notApplicable`) agrees between `modalApplyOneS5` and K's `modalApplyOne`, even
though the literal `RuleResult` constructor can differ for the two S5-relevant shapes (K's
`.notApplicable` upgraded to `.persistent` when the universal-propagation set is nonempty --
`.persistent` either way is still bucketed with the "unchanged" case). This is the fact Phase 4's
`outDegEq` preservation needs to identify `modalStepBranchS5gKeyed`'s (non-minting-shape)
`e'`-output with K's own per-call `outDeg` obligation (`modalApplyOne_outDeg_step`). -/
lemma modalApplyOneS5_eshape_eq
    (sf : SignedFormula (Proposition Atom) WorldIndex)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility) :
    (match (modalApplyOneS5 sf b acc).fst with
      | .linear _ => e ++ [sf]
      | .branching _ => e ++ [sf]
      | .persistent _ => e
      | .notApplicable => e) =
    (match (modalApplyOne sf b acc).fst with
      | .linear _ => e ++ [sf]
      | .branching _ => e ++ [sf]
      | .persistent _ => e
      | .notApplicable => e) := by
  unfold modalApplyOneS5
  rcases hp : modalApplyOne sf b acc with ⟨kResult, kAcc⟩
  simp only [hp]
  rcases hs : sf.sign with _ | _ <;> rcases hf : sf.formula with _ | _ | _ | _ | _ | φ | φ <;>
    simp_all <;>
    rcases kResult with _ | _ | _ | _ <;> simp <;> split_ifs <;> simp

/-! ## S5 Minting Guard (task 515 Phase 2)

The termination machinery's minting guard: `successorBirthContentS5`/`blockingWorldS5` mirror
`successorBirthContent`/`blockingWorldS4` (`LoopChecking.lean:374/391`) exactly. Both are
already `φ₀`-parametric and rule-independent (they only inspect the branch `b`'s box-context at
the trigger world `w`, never any S4-specific rule), so the S5 versions reuse the S4
declarations verbatim under new names, matching the plan's Phase 2 artifact list and keeping
S4/S5 development decoupled. -/

/-- The prospective birth content of the successor that would be minted for the modal-minting
call at `⟨s, φ, w⟩` (the two K minting shapes `F(□φ)@w`/`T(◇φ)@w`, `s` the witness's sign) at
branch `b`. Reuses `successorBirthContent` (`LoopChecking.lean:374`) verbatim -- the
computation is purely a function of what is already on `b` at `w`, independent of which
system's tableau triggered the mint. -/
def successorBirthContentS5 (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex))
    (s : Sign) (φ : Proposition Atom) (w : WorldIndex) : Finset (Sign × Proposition Atom) :=
  successorBirthContent φ₀ b s φ w

/-- The S5 minting guard: the least world `w' ∈ modalKnownWorlds b` whose CURRENT relevant set
(`relevantSetFinset`) already equals the PROSPECTIVE successor's birth content
(`successorBirthContentS5`), if any exists. Mirrors `blockingWorldS4`
(`LoopChecking.lean:391`) exactly, with `successorBirthContentS5` swapped in. `none` means no
blocking world exists (the underlying rule should mint a fresh world); `some wBlock` means the
prospective successor should be loop-backed to `wBlock` instead. -/
def blockingWorldS5 (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex))
    (s : Sign) (φ : Proposition Atom) (w : WorldIndex) : Option WorldIndex :=
  ((modalKnownWorlds b).filter
    (fun w' => decide (relevantSetFinset φ₀ b w' = successorBirthContentS5 φ₀ b s φ w))).min?

omit [Hashable Atom] in
/-- If `blockingWorldS5` returns a world, it is a known world of the branch. Mirrors
`blockingWorldS4_mem_modalKnownWorlds` (`LoopChecking.lean:399`). -/
lemma blockingWorldS5_mem_modalKnownWorlds (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (s : Sign) (φ : Proposition Atom)
    (w wBlock : WorldIndex) (h : blockingWorldS5 φ₀ b s φ w = some wBlock) :
    wBlock ∈ modalKnownWorlds b := by
  have hmem := List.min?_mem h
  exact (List.mem_filter.mp hmem).1

omit [Hashable Atom] in
/-- **The guard contract**: if `blockingWorldS5` returns a world, that world's CURRENT relevant
set equals the prospective successor's birth content. Mirrors `blockingWorldS4_eq_birthContent`
(`LoopChecking.lean:413`). -/
lemma blockingWorldS5_eq_birthContent (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (s : Sign) (φ : Proposition Atom)
    (w wBlock : WorldIndex) (h : blockingWorldS5 φ₀ b s φ w = some wBlock) :
    relevantSetFinset φ₀ b wBlock = successorBirthContentS5 φ₀ b s φ w := by
  have hmem := List.min?_mem h
  have hpred := (List.mem_filter.mp hmem).2
  exact of_decide_eq_true hpred

omit [Hashable Atom] in
/-- **The guard's freshness contract**: if `blockingWorldS5` returns `none`, the prospective
successor's birth content differs from every existing known world's CURRENT relevant set.
Mirrors `blockingWorldS4_none_fresh` (`LoopChecking.lean:426`). -/
lemma blockingWorldS5_none_fresh (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (s : Sign) (φ : Proposition Atom)
    (w : WorldIndex) (h : blockingWorldS5 φ₀ b s φ w = none) :
    ∀ w' ∈ modalKnownWorlds b, relevantSetFinset φ₀ b w' ≠ successorBirthContentS5 φ₀ b s φ w := by
  unfold blockingWorldS5 at h
  rw [List.min?_eq_none_iff, List.filter_eq_nil_iff] at h
  intro w' hw' heq
  exact absurd (decide_eq_true heq) (by simpa using h w' hw')

/-! ## S5 Guarded Rule Application (task 515 Phase 2)

`modalApplyOneS5g` routes the two K minting shapes (`F(□φ)@w`, `T(◇φ)@w` -- disjoint from the
S5 universal-propagation shapes `T(□φ)@w`/`F(◇φ)@w`) through `blockingWorldS5`, mirroring
`modalApplyOneS4` (`LoopChecking.lean:461`); every other shape (including both S5 universal
arms) falls through unchanged to `modalApplyOneS5`. Unlike S4 (which falls through to
`modalApplyOneS4Rules`, an extra K+T+4 dispatch layer), S5 has no intermediate rule layer, so
the unblocked/agreement lemmas below are direct, not chained through a T-style rule stack. -/

/-- The guarded S5 rule-application function (Decision D2's replacement for the abandoned
`RuleApplicationSpec modalApplyOneS5` route): at the two K minting shapes, consult
`blockingWorldS5` before minting; everywhere else (including the S5 universal arms), reduce to
`modalApplyOneS5` unchanged. Mirrors `modalApplyOneS4` (`LoopChecking.lean:461`). -/
def modalApplyOneS5g (φ₀ : Proposition Atom) : RuleApply Atom :=
  fun sf b acc =>
    match sf.sign, sf.formula with
    | .neg, .box φ =>
      match blockingWorldS5 φ₀ b .neg φ sf.label with
      | some wBlock => (.linear [], acc.addEdge sf.label wBlock)
      | none => modalApplyOneS5 sf b acc
    | .pos, .diamond φ =>
      match blockingWorldS5 φ₀ b .pos φ sf.label with
      | some wBlock => (.linear [], acc.addEdge sf.label wBlock)
      | none => modalApplyOneS5 sf b acc
    | _, _ => modalApplyOneS5 sf b acc

/-- Guard spec (a), box-negative shape: `modalApplyOneS5g φ₀` at `F(□φ)@w` blocks -- adding
exactly one loop-back edge to an existing known world and minting no new world -- when the
guard fires. Mirrors `modalApplyOneS4_boxNeg_blocked_eq` (`LoopChecking.lean:479`). -/
lemma modalApplyOneS5g_boxNeg_blocked_eq (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (φ : Proposition Atom) (w wBlock : WorldIndex)
    (hblock : blockingWorldS5 φ₀ b .neg φ w = some wBlock) :
    modalApplyOneS5g φ₀ ⟨.neg, .box φ, w⟩ b acc = (.linear [], acc.addEdge w wBlock) := by
  unfold modalApplyOneS5g
  simp [hblock]

/-- Guard spec (b), box-negative shape, unblocked case: `modalApplyOneS5g φ₀` reduces to
`modalApplyOneS5` directly (no intermediate rule layer, unlike S4's `modalApplyOneS4Rules`
chain). Mirrors `modalApplyOneS4_boxNeg_unblocked_eq` (`LoopChecking.lean:488`). -/
lemma modalApplyOneS5g_boxNeg_unblocked_eq (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (φ : Proposition Atom) (w : WorldIndex) (hblock : blockingWorldS5 φ₀ b .neg φ w = none) :
    modalApplyOneS5g φ₀ ⟨.neg, .box φ, w⟩ b acc = modalApplyOneS5 ⟨.neg, .box φ, w⟩ b acc := by
  unfold modalApplyOneS5g
  simp [hblock]

/-- Guard spec (a), diamond-positive shape (dual of the box-negative pair): blocked case adds
exactly one loop-back edge and mints no new world. Mirrors `modalApplyOneS4_diaPos_blocked_eq`
(`LoopChecking.lean:500`). -/
lemma modalApplyOneS5g_diaPos_blocked_eq (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (φ : Proposition Atom) (w wBlock : WorldIndex)
    (hblock : blockingWorldS5 φ₀ b .pos φ w = some wBlock) :
    modalApplyOneS5g φ₀ ⟨.pos, .diamond φ, w⟩ b acc = (.linear [], acc.addEdge w wBlock) := by
  unfold modalApplyOneS5g
  simp [hblock]

/-- Guard spec (b), diamond-positive shape, unblocked case: reduces to `modalApplyOneS5`
directly. Mirrors `modalApplyOneS4_diaPos_unblocked_eq` (`LoopChecking.lean:510`). -/
lemma modalApplyOneS5g_diaPos_unblocked_eq (φ₀ : Proposition Atom)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (φ : Proposition Atom) (w : WorldIndex) (hblock : blockingWorldS5 φ₀ b .pos φ w = none) :
    modalApplyOneS5g φ₀ ⟨.pos, .diamond φ, w⟩ b acc =
      modalApplyOneS5 ⟨.pos, .diamond φ, w⟩ b acc := by
  unfold modalApplyOneS5g
  simp [hblock]

/-- `modalApplyOneS5g` agrees with `modalApplyOneS5` outside the two K minting shapes: the
guard only ever intervenes at `F(□φ)@w`/`T(◇φ)@w`. Mirrors
`modalApplyOneS4_eq_of_not_boxNeg_diaPos` (`LoopChecking.lean:522`). -/
lemma modalApplyOneS5g_eq_of_not_boxNeg_diaPos
    (φ₀ : Proposition Atom) (sf : SignedFormula (Proposition Atom) WorldIndex)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (h : ¬ (sf.sign = .neg ∧ ∃ φ, sf.formula = .box φ) ∧
         ¬ (sf.sign = .pos ∧ ∃ φ, sf.formula = .diamond φ)) :
    modalApplyOneS5g φ₀ sf b acc = modalApplyOneS5 sf b acc := by
  obtain ⟨h1, h2⟩ := h
  unfold modalApplyOneS5g
  rcases hs : sf.sign with _ | _ <;> rcases hf : sf.formula with _ | _ | _ | _ | _ | φ | φ <;>
    simp_all

/-- `modalApplyOneS5g` agrees with K's `modalApplyOne` outside **all four** of the shapes
either the guard or the S5 universal arms touch (the two K minting shapes AND the two S5
universal-propagation shapes): composes `modalApplyOneS5g_eq_of_not_boxNeg_diaPos` with
`modalApplyOneS5_eq_of_not_boxPos_diaNeg` (`S5Simplification.lean:243`), the reuse the plan's
Phase 2 task calls for. -/
lemma modalApplyOneS5g_eq_of_not_minting_not_universal
    (φ₀ : Proposition Atom) (sf : SignedFormula (Proposition Atom) WorldIndex)
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (hmint : ¬ (sf.sign = .neg ∧ ∃ φ, sf.formula = .box φ) ∧
             ¬ (sf.sign = .pos ∧ ∃ φ, sf.formula = .diamond φ))
    (huniv : ¬ (sf.sign = .pos ∧ ∃ φ, sf.formula = .box φ) ∧
             ¬ (sf.sign = .neg ∧ ∃ φ, sf.formula = .diamond φ)) :
    modalApplyOneS5g φ₀ sf b acc = modalApplyOne sf b acc := by
  rw [modalApplyOneS5g_eq_of_not_boxNeg_diaPos φ₀ sf b acc hmint,
    modalApplyOneS5_eq_of_not_boxPos_diaNeg sf b acc huniv]

/-! ## S5 Driver Instantiation -/

/-- One-step branch expansion for the S5 (equivalence-frame) tableau: the generic driver
(`modalStepBranchGen`, `Saturation.lean`) instantiated at `apply := modalApplyOneS5`. -/
def modalStepBranchS5
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility) :
    Option (List (List (SignedFormula (Proposition Atom) WorldIndex)) ×
            List (List (SignedFormula (Proposition Atom) WorldIndex)) ×
            Accessibility) :=
  modalStepBranchGen modalApplyOneS5 b e acc

/-- Fuel-based expansion of a list of S5-system branches: the generic driver
(`modalExpandBranchesGen`, `Saturation.lean`) instantiated at `apply := modalApplyOneS5`. -/
def modalExpandBranchesS5
    (branches expandedSets : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (accs : List Accessibility) (fuel : Nat) : ModalTableauResult Atom :=
  modalExpandBranchesGen modalApplyOneS5 branches expandedSets accs fuel

/-- The S5-system (equivalence-frame) modal tableau decision procedure: the generic entry point
(`modalTableauGen`, `Saturation.lean`) instantiated at `apply := modalApplyOneS5`, starting the
signed tableau from `F(φ)` at world `0` (same fuel bound as K: S5 never mints a world outside
the K `diamondPos`/`boxNeg` arms, so `modalFuel` is sufficient here too). -/
def modalTableauS5 (φ : Proposition Atom) : ModalTableauResult Atom :=
  modalTableauGen modalApplyOneS5 φ

/-- `modalStepBranchS5` is exactly `modalStepBranchGen modalApplyOneS5` -- true `rfl`. -/
theorem modalStepBranchS5_eq
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility) :
    modalStepBranchS5 b e acc = modalStepBranchGen modalApplyOneS5 b e acc := rfl

/-- `modalExpandBranchesS5` is exactly `modalExpandBranchesGen modalApplyOneS5` -- true `rfl`. -/
theorem modalExpandBranchesS5_eq
    (branches expandedSets : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (accs : List Accessibility) (fuel : Nat) :
    modalExpandBranchesS5 branches expandedSets accs fuel =
      modalExpandBranchesGen modalApplyOneS5 branches expandedSets accs fuel := rfl

/-- `modalTableauS5` is exactly `modalTableauGen modalApplyOneS5` -- true `rfl`. -/
theorem modalTableauS5_eq (φ : Proposition Atom) :
    modalTableauS5 φ = modalTableauGen modalApplyOneS5 φ := rfl

/-! ## `modalKnownWorlds` Local Re-Derivations (task 515 Phase 3)

`FmpMeasure.lean`'s `mem_modalKnownWorlds`/`modalKnownWorlds_mono_append` are `private` (hence
unavailable across files). Local re-derivation, mirroring `BDriver.lean`'s established pattern
(`mem_modalKnownWorlds_B`/`modalKnownWorlds_mono_append_B`), renamed for S5. -/

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `FmpMeasure.lean`'s `private lemma modalKnownWorlds_fold_spec`
(unavailable across files), dropping the `Nodup` conjunct this development does not need.
Mirrors `BDriver.lean`'s `modalKnownWorlds_fold_spec_B`. -/
private lemma modalKnownWorlds_fold_spec_S5
    (l : List (SignedFormula (Proposition Atom) WorldIndex)) (ws0 : List WorldIndex) :
    ∀ x, x ∈ l.foldl (fun ws sf => if ws.any (· == sf.label) then ws else sf.label :: ws) ws0 ↔
      x ∈ ws0 ∨ ∃ sf ∈ l, sf.label = x := by
  induction l generalizing ws0 with
  | nil => simp
  | cons sf rest ih =>
    by_cases hc : ws0.any (· == sf.label)
    · simp only [List.foldl_cons, if_pos hc]
      intro x
      rw [ih ws0]
      have hmemws0 : sf.label ∈ ws0 := by simpa [List.any_eq_true] using hc
      constructor
      · rintro (h | ⟨sf', hsf', rfl⟩)
        · exact Or.inl h
        · exact Or.inr ⟨sf', List.mem_cons_of_mem _ hsf', rfl⟩
      · rintro (h | ⟨sf', hsf', hfeq⟩)
        · exact Or.inl h
        · rcases List.mem_cons.mp hsf' with rfl | hsf'
          · exact Or.inl (hfeq ▸ hmemws0)
          · exact Or.inr ⟨sf', hsf', hfeq⟩
    · simp only [List.foldl_cons, if_neg hc]
      intro x
      rw [ih (sf.label :: ws0)]
      constructor
      · rintro (h | ⟨sf', hsf', rfl⟩)
        · rcases List.mem_cons.mp h with rfl | h
          · exact Or.inr ⟨sf, List.mem_cons_self, rfl⟩
          · exact Or.inl h
        · exact Or.inr ⟨sf', List.mem_cons_of_mem _ hsf', rfl⟩
      · rintro (h | ⟨sf', hsf', hfeq⟩)
        · exact Or.inl (List.mem_cons_of_mem _ h)
        · rcases List.mem_cons.mp hsf' with rfl | hsf'
          · exact Or.inl (hfeq ▸ List.mem_cons_self)
          · exact Or.inr ⟨sf', hsf', hfeq⟩

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `FmpMeasure.lean`'s `private lemma mem_modalKnownWorlds`
(unavailable across files). Mirrors `BDriver.lean`'s `mem_modalKnownWorlds_B`. -/
private lemma mem_modalKnownWorlds_S5
    (l : List (SignedFormula (Proposition Atom) WorldIndex)) (x : WorldIndex) :
    x ∈ modalKnownWorlds l ↔ ∃ sf ∈ l, sf.label = x := by
  unfold modalKnownWorlds
  simpa using modalKnownWorlds_fold_spec_S5 l [] x

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `FmpMeasure.lean`'s `private lemma modalKnownWorlds_mono_append`
(unavailable across files): appending formulas to the front of a branch only grows its
known-worlds set. Mirrors `BDriver.lean`'s `modalKnownWorlds_mono_append_B`. -/
private lemma modalKnownWorlds_mono_append_S5
    (xs b : List (SignedFormula (Proposition Atom) WorldIndex)) :
    ∀ x ∈ modalKnownWorlds b, x ∈ modalKnownWorlds (xs ++ b) := by
  intro x hx
  rw [mem_modalKnownWorlds_S5] at hx ⊢
  obtain ⟨sf, hsf, rfl⟩ := hx
  exact ⟨sf, List.mem_append_right _ hsf, rfl⟩

/-! ## Keys-Aware Guard Redesign (task 515 Phase 3, v2)

`blockingWorldS5` (Phase 2) compares the prospective successor's birth content against every
known world's CURRENT (live) relevant set. Task 511's S4 development hit the identical guard-vs-
live-set obstruction: a world born with key `k` can later grow its live relevant set past `k`,
so a *different* freshly-minted world computing the *same* birth content `k` is not blocked by
the live-set guard (its own live set has already grown away from `k`), yet `keysDistinct`
demands the two worlds' *birth keys* differ. The v2 fix (task 511's documented resolution,
adopted verbatim in shape): compare the prospective birth content against the threaded
**stored keys** list directly. Keys are fixed at minting time and never change, so this
comparison is exact and the resulting `_none_fresh` contract is precisely the birth-key
invariant `keysDistinct` (Phase 5) needs. -/

/-- The keys-aware S5 minting guard (v2, supersedes `blockingWorldS5` for the minting decision):
the least *stored* world `w'` among `keys` whose STORED birth key already equals the PROSPECTIVE
successor's birth content (`successorBirthContentS5`), if any exists. Mirrors the *intent* of
`blockingWorldS4`/`blockingWorldS5` but keys the comparison on the threaded `keys` list, per task
511's documented fix (511 summary "Next Steps"; report Section 4 Option A2). `none` means no
blocking world exists (mint fresh); `some wBlock` means loop-back to `wBlock`. -/
def blockingWorldS5Keyed (φ₀ : Proposition Atom)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (b : List (SignedFormula (Proposition Atom) WorldIndex))
    (s : Sign) (φ : Proposition Atom) (w : WorldIndex) : Option WorldIndex :=
  ((keys.filter
    (fun p => decide (p.2 = successorBirthContentS5 φ₀ b s φ w))).map Prod.fst).min?

omit [Hashable Atom] in
/-- **The keyed guard contract**: if `blockingWorldS5Keyed` returns a world, that world's
STORED birth key equals the prospective successor's birth content. Mirrors
`blockingWorldS5_eq_birthContent`, keyed on `keys` rather than the live relevant set. -/
lemma blockingWorldS5Keyed_eq_birthContent (φ₀ : Proposition Atom)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (s : Sign) (φ : Proposition Atom)
    (w wBlock : WorldIndex) (h : blockingWorldS5Keyed φ₀ keys b s φ w = some wBlock) :
    (wBlock, successorBirthContentS5 φ₀ b s φ w) ∈ keys := by
  unfold blockingWorldS5Keyed at h
  have hmem := List.min?_mem h
  obtain ⟨p, hp, hpfst⟩ := List.mem_map.mp hmem
  obtain ⟨hpmem, hpdec⟩ := List.mem_filter.mp hp
  have hpeq : p.2 = successorBirthContentS5 φ₀ b s φ w := of_decide_eq_true hpdec
  obtain ⟨pw, pk⟩ := p
  simp only at hpfst hpeq
  subst hpfst
  subst hpeq
  exact hpmem

omit [Hashable Atom] in
/-- **The keyed guard's freshness contract**: if `blockingWorldS5Keyed` returns `none`, the
prospective successor's birth content differs from EVERY stored key in `keys`. **This is the
birth-key invariant that makes `keysDistinct` a genuine per-step invariant** (directly discharges
the new-vs-old case in Phase 5). Mirrors `blockingWorldS5_none_fresh`/`blockingWorldS4_none_fresh`,
keyed on `keys`. -/
lemma blockingWorldS5Keyed_none_fresh (φ₀ : Proposition Atom)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (b : List (SignedFormula (Proposition Atom) WorldIndex)) (s : Sign) (φ : Proposition Atom)
    (w : WorldIndex) (h : blockingWorldS5Keyed φ₀ keys b s φ w = none) :
    ∀ w' k, (w', k) ∈ keys → k ≠ successorBirthContentS5 φ₀ b s φ w := by
  unfold blockingWorldS5Keyed at h
  rw [List.min?_eq_none_iff, List.map_eq_nil_iff, List.filter_eq_nil_iff] at h
  intro w' k hmem heq
  exact absurd (decide_eq_true heq) (by simpa using h (w', k) hmem)

/-! ## Key-Threaded S5 Guarded Step (task 515 Phase 3, v2)

Mirrors `LoopChecking.lean`'s `modalStepBranchS4Keyed` (task 511 Phase 4): threads a stable
per-world birth-key list `keys` alongside `(b, e, acc)`, gaining an entry exactly when the guard
is unblocked at one of the two K minting shapes. **v2 crux change**: the block/mint decision is
now computed here directly via `blockingWorldS5Keyed` (the keys-aware guard), bypassing
`modalApplyOneS5g`'s live-set dispatch on the two minting shapes entirely (R2: "keys-aware bypass
inside a redesigned stepper"). Every other shape (including both S5 universal-propagation arms)
still delegates to `modalApplyOneS5` unchanged, so the non-minting agreement lemmas
(`modalApplyOneS5g_eq_of_not_boxNeg_diaPos`, Phase 2) remain valid, undisturbed reference
material even though this stepper no longer calls `modalApplyOneS5g` on the minting shapes. -/

/-- The S5-specific keyed one-step branch expansion (v2): mirrors `modalStepBranchS4Keyed`
(`LoopChecking.lean:582`) for the `(newBranches, newExpandedSets, newAcc)` triple, additionally
threading `keys`. At the two K minting shapes, the keyed guard `blockingWorldS5Keyed` decides
block (loop-back edge to the stored world, no new formulas) vs. mint (delegate to
`modalApplyOneS5` -- equal to K's `modalApplyOne` here since minting shapes are disjoint from
the S5 universal shapes, `modalApplyOneS5_eq_of_not_boxPos_diaNeg`), appending the fresh key to
`keys` on an unblocked mint. Every other shape delegates to `modalApplyOneS5` with `keys`
unchanged. -/
def modalStepBranchS5gKeyed (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom))) :
    Option (List (List (SignedFormula (Proposition Atom) WorldIndex)) ×
            List (List (SignedFormula (Proposition Atom) WorldIndex)) ×
            Accessibility ×
            List (WorldIndex × Finset (Sign × Proposition Atom))) :=
  b.findSome? fun sf =>
    if e.any (· == sf) then none
    else
      match sf.sign, sf.formula with
      | .neg, .box φ =>
        match blockingWorldS5Keyed φ₀ keys b .neg φ sf.label with
        | some wBlock => some ([b], [e ++ [sf]], acc.addEdge sf.label wBlock, keys)
        | none =>
          let (result, newAcc) := modalApplyOneS5 sf b acc
          let keys' := keys ++ [(modalNextWorld b, successorBirthContentS5 φ₀ b .neg φ sf.label)]
          match result with
          | .linear newForms => some ([newForms ++ b], [e ++ [sf]], newAcc, keys')
          | .branching branches =>
            some (branches.map (· ++ b), branches.map (fun _ => e ++ [sf]), newAcc, keys')
          | .persistent newForms => some ([newForms ++ b], [e], newAcc, keys')
          | .notApplicable => none
      | .pos, .diamond φ =>
        match blockingWorldS5Keyed φ₀ keys b .pos φ sf.label with
        | some wBlock => some ([b], [e ++ [sf]], acc.addEdge sf.label wBlock, keys)
        | none =>
          let (result, newAcc) := modalApplyOneS5 sf b acc
          let keys' := keys ++ [(modalNextWorld b, successorBirthContentS5 φ₀ b .pos φ sf.label)]
          match result with
          | .linear newForms => some ([newForms ++ b], [e ++ [sf]], newAcc, keys')
          | .branching branches =>
            some (branches.map (· ++ b), branches.map (fun _ => e ++ [sf]), newAcc, keys')
          | .persistent newForms => some ([newForms ++ b], [e], newAcc, keys')
          | .notApplicable => none
      | _, _ =>
        let (result, newAcc) := modalApplyOneS5 sf b acc
        match result with
        | .linear newForms => some ([newForms ++ b], [e ++ [sf]], newAcc, keys)
        | .branching branches =>
          some (branches.map (· ++ b), branches.map (fun _ => e ++ [sf]), newAcc, keys)
        | .persistent newForms => some ([newForms ++ b], [e], newAcc, keys)
        | .notApplicable => none

/-! ## The S5 Loop Invariant `S5LoopInv` (task 515 Phase 3, v2: extended to ten fields)

**v2 crux change**: extends the v1 four-field `S5LoopInv` to the full ten-field shape mirroring
the landed `S4LoopInv` (`LoopChecking.lean:1127`), adding the six generic driver-bookkeeping
fields (`bClosure`/`eNodup`/`eClosure`/`accFresh`/`accKnown`/`outDegEq`) the v1 four-field
structure lacked. `accKnown` (= `accTargetsKnown`) is the exact standing hypothesis
`modalApplyOne_knownWorlds_step` (`FmpMeasure.lean:2042`) demands; `bClosure` (⊆
`modalUniverseS5 φ₀`) supplies the subformula-closure fact needed to place a newly-inserted
birth-key pair inside `signedSubfmls φ₀`. The four birth-key fields are carried unchanged from
v1 (same statements), but `keysDistinct` is now discharged by the keys-aware guard
(`blockingWorldS5Keyed_none_fresh`) rather than resisting as in the v1 live-set design. -/

/-- **v2 extended structure**: `S5LoopInv` mirrors `S4LoopInv`'s ten fields
(`LoopChecking.lean:1127`) exactly, `S4` swapped for `S5` throughout (`modalUniverseS4` ->
`modalUniverseS5`), stated over the threaded `keys` list (`modalStepBranchS5gKeyed`) rather than
the live branch for the four birth-key fields. -/
structure S5LoopInv (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom))) : Prop where
  /-- Every branch formula is a member of the fixed finite S5 universe `U_{S5}(φ₀)`. -/
  bClosure : ∀ x ∈ b, x ∈ modalUniverseS5 φ₀
  /-- The expanded set has no duplicate entries. -/
  eNodup : e.Nodup
  /-- Every expanded-set formula is a member of `U_{S5}(φ₀)`. -/
  eClosure : ∀ x ∈ e, x ∈ modalUniverseS5 φ₀
  /-- All of `acc`'s recorded worlds are `< modalNextWorld b`. -/
  accFresh : accFreshInv b acc
  /-- Every `acc`-edge target is a label already appearing on the branch. -/
  accKnown : accTargetsKnown b acc
  /-- `outDeg` exactly counts the minting-shaped formulas in `e` at each world. -/
  outDegEq : ∀ w, outDeg acc w = (e.filter (fun x => x.label == w && isMintingShaped x)).length
  /-- Every known world has a recorded birth key. -/
  keysTotal : ∀ w ∈ modalKnownWorlds b, ∃ k, (w, k) ∈ keys
  /-- A world's recorded birth key is a LOWER BOUND on its live relevant set: monotone-stable,
  since birth keys never change after a world is born and live relevant sets only grow
  (`relevantSetFinset_mono`). -/
  keyLowerBd : ∀ w k, (w, k) ∈ keys → k ⊆ relevantSetFinset φ₀ b w
  /-- Distinct worlds have DISTINCT birth keys: the hypothesis the pigeonhole argument
  (`modalKnownWorlds_length_le_worldBoundS5`, Phase 6) consumes. Now discharged via the
  keys-aware guard (`blockingWorldS5Keyed_none_fresh`), not live-set reasoning. -/
  keysDistinct : ∀ w w' k k', (w, k) ∈ keys → (w', k') ∈ keys → w ≠ w' → k ≠ k'
  /-- Birth keys are drawn from the powerset of the finite signed-subformula codomain
  `signedSubfmls φ₀`: the pigeonhole argument's injection target (Phase 6). -/
  keysInUniverse : ∀ w k, (w, k) ∈ keys → k ⊆ signedSubfmls φ₀
  /-- Every recorded key's world is a known world of the branch: the fact
  `blockingWorldS5Keyed`'s stored-key guard needs (in place of `blockingWorldS5`'s free
  `blockingWorldS5_mem_modalKnownWorlds` corollary of filtering over `modalKnownWorlds b`
  directly) to justify that a loop-back edge to a stored key's world targets a known world
  (feeds `accKnown` preservation, Phase 4). Maintained alongside `keysTotal` as the converse
  membership direction; both grow only by appending a freshly-minted, immediately-known world. -/
  keysKnown : ∀ w k, (w, k) ∈ keys → w ∈ modalKnownWorlds b

/-! ## Generic-Field Preservation Lemmas (task 515 Phase 4)

Proves that a `modalStepBranchS5gKeyed` step preserves the six generic (rule-independent)
`S5LoopInv` fields. **No template**: the existing generic `_gen` wrappers
(`modalStepBranch_preserves_accTargetsKnown_gen`, `modalStepBranch_knownWorlds_gen`, etc.,
`FmpMeasure.lean`) all presuppose the `hFreshLocal` dichotomy (`acc` unchanged, or exactly one
edge to a genuinely FRESH world) -- but the keyed guard's *blocked* case adds a loop-back edge to
an *existing* (known, non-fresh) world, which fits neither disjunct. So these lemmas are proved
directly by case analysis on `modalStepBranchS5gKeyed`'s own three-way dispatch (blocked / mint /
non-minting), reusing K's own per-call lemmas (`modalApplyOne_knownWorlds_step`,
`modalApplyOne_boxNeg_witness`/`_diamondPos_witness`) on the shapes where the keyed stepper
provably agrees with K, rather than routing through the generic wrappers. -/

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `Soundness.lean`'s `private lemma hasEdge_addEdge_cases`
(unavailable across files): decompose membership of an edge in `acc.addEdge w w'`. Mirrors
`BDriver.lean`'s `hasEdge_addEdge_cases_B`. -/
private lemma hasEdge_addEdge_cases_S5 {acc : Accessibility} {w w' a a' : WorldIndex}
    (h : (acc.addEdge w w').hasEdge a a' = true) :
    (a = w ∧ a' = w') ∨ acc.hasEdge a a' = true := by
  simp only [Accessibility.addEdge, Accessibility.hasEdge, List.any_cons, Bool.or_eq_true,
    Bool.and_eq_true, beq_iff_eq] at h
  tauto

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `FmpMeasure.lean`'s `private lemma outDeg_addEdge_self` (unavailable
across files): `outDeg` under `addEdge` at the matching source extends the successor list by
exactly the new target, incrementing `outDeg` by 1. -/
private lemma outDeg_addEdge_self_S5 (acc : Accessibility) (w wf : WorldIndex) :
    outDeg (acc.addEdge w wf) w = outDeg acc w + 1 := by
  simp [outDeg, Accessibility.successorsOf, Accessibility.addEdge]

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `FmpMeasure.lean`'s `private lemma outDeg_addEdge_ne` (unavailable
across files): `outDeg` under `addEdge` is unchanged at any world other than the edge's
source. -/
private lemma outDeg_addEdge_ne_S5 (acc : Accessibility) (w wf w' : WorldIndex) (h : w' ≠ w) :
    outDeg (acc.addEdge w wf) w' = outDeg acc w' := by
  simp only [outDeg, Accessibility.successorsOf, Accessibility.addEdge, List.filterMap_cons]
  have : (w == w') = false := by simp only [beq_eq_false_iff_ne]; exact fun heq => h heq.symm
  simp [this]

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `FmpMeasure.lean`'s `private lemma filter_minting_append_of_minting_at`
(unavailable across files): appending a minting-shaped formula at label `sf.label` to the
expanded set extends the minting-filtered count at `sf.label` by exactly the singleton `[sf]`. -/
private lemma filter_minting_append_of_minting_at_S5
    (e : List (SignedFormula (Proposition Atom) WorldIndex))
    (sf : SignedFormula (Proposition Atom) WorldIndex) (h : isMintingShaped sf = true) :
    (e ++ [sf]).filter (fun x => x.label == sf.label && isMintingShaped x) =
      e.filter (fun x => x.label == sf.label && isMintingShaped x) ++ [sf] := by
  rw [List.filter_append]
  simp [h]

omit [DecidableEq Atom] [Hashable Atom] in
/-- Local re-derivation of `FmpMeasure.lean`'s `private lemma filter_minting_append_of_minting_ne`
(unavailable across files): appending a minting-shaped formula at label `sf.label` to the
expanded set leaves the minting-filtered count at any *other* world `w` unchanged. -/
private lemma filter_minting_append_of_minting_ne_S5
    (e : List (SignedFormula (Proposition Atom) WorldIndex))
    (sf : SignedFormula (Proposition Atom) WorldIndex) (w : WorldIndex) (hw : w ≠ sf.label) :
    (e ++ [sf]).filter (fun x => x.label == w && isMintingShaped x) =
      e.filter (fun x => x.label == w && isMintingShaped x) := by
  rw [List.filter_append]
  have : (sf.label == w) = false := by
    simp only [beq_eq_false_iff_ne]; exact fun h => hw h.symm
  simp [this]

omit [Hashable Atom] in
/-- Characterization of the expanded-set shape a `modalStepBranchS5gKeyed` step can produce:
every child expanded set is either `e ++ [sf]` (linear/blocked-loop-back-shaped) or `e` unchanged
(persistent-shaped), where `sf` is the trigger formula the step fired on and `sf ∉ e`. This is
the one fact all six generic-field preservation lemmas' `e`-component reasoning shares, so it is
factored out once. -/
private lemma modalStepBranchS5gKeyed_expanded_shape (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (newBs newExps : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (newAcc : Accessibility) (newKeys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (hstep : modalStepBranchS5gKeyed φ₀ b e acc keys = some (newBs, newExps, newAcc, newKeys)) :
    ∃ sf ∈ b, sf ∉ e ∧ ∀ e' ∈ newExps, e' = e ++ [sf] ∨ e' = e := by
  unfold modalStepBranchS5gKeyed at hstep
  obtain ⟨sf, hsfmem, hsf⟩ := List.exists_of_findSome?_eq_some hstep
  clear hstep
  by_cases hexp : e.any (· == sf) = true
  · simp only [hexp, if_true] at hsf
    exact absurd hsf (by simp)
  · rw [if_neg (by simpa using hexp)] at hsf
    refine ⟨sf, hsfmem, by simpa using hexp, ?_⟩
    clear hsfmem hexp
    split at hsf <;> repeat' split at hsf
    all_goals try injection hsf
    all_goals
      (rename_i hsf
       simp only [Prod.mk.injEq] at hsf
       intro e' he'
       first
       | (rw [← hsf.2.1] at he'; simp only [List.mem_singleton] at he'; exact Or.inl he')
       | (rw [← hsf.2.1] at he'
          obtain ⟨br, -, rfl⟩ := List.mem_map.mp he'; exact Or.inl rfl)
       | (rw [← hsf.2.1] at he'; simp only [List.mem_singleton] at he'; exact Or.inr he'))

omit [Hashable Atom] in
/-- Characterization of the accessibility/branch-list shape a `modalStepBranchS5gKeyed` step
can produce (mirrors `modalStepBranchS5gKeyed_expanded_shape`'s pattern for the `newAcc`/`newBs`
components instead of `newExps`). Every step is either a **blocked** (loop-back) step --
`newBs = [b]` unchanged, `newAcc = acc.addEdge sf.label wBlock` for a *known* `wBlock` -- or a
step whose accessibility output is exactly `(modalApplyOneS5 sf b acc).snd` (uniformly,
regardless of whether `sf` is one of the two K-minting shapes or any other shape, by
`modalApplyOneS5_snd_eq`), with `newBs` built from `(modalApplyOneS5 sf b acc).fst`'s
`RuleResult` shape the same three ways `modalStepBranchS5gKeyed_expanded_shape` characterizes
`newExps`. Shared case dispatch for the remaining Phase 4 fields
(`accFresh`/`accKnown`/`outDegEq`). -/
private lemma modalStepBranchS5gKeyed_acc_shape (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (newBs newExps : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (newAcc : Accessibility) (newKeys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (hstep : modalStepBranchS5gKeyed φ₀ b e acc keys = some (newBs, newExps, newAcc, newKeys))
    (hkK : ∀ w k, (w, k) ∈ keys → w ∈ modalKnownWorlds b) :
    ∃ sf ∈ b, sf ∉ e ∧
      ((∃ wBlock, wBlock ∈ modalKnownWorlds b ∧ newAcc = acc.addEdge sf.label wBlock ∧
          newBs = [b] ∧ newExps = [e ++ [sf]] ∧ isMintingShaped sf = true) ∨
       (newAcc = (modalApplyOneS5 sf b acc).snd ∧
        (match (modalApplyOneS5 sf b acc).fst with
          | .linear nf => newBs = [nf ++ b] ∧ newExps = [e ++ [sf]]
          | .branching brs => newBs = brs.map (· ++ b) ∧ newExps = brs.map (fun _ => e ++ [sf])
          | .persistent nf => newBs = [nf ++ b] ∧ newExps = [e]
          | .notApplicable => False))) := by
  unfold modalStepBranchS5gKeyed at hstep
  obtain ⟨sf, hsfmem, hsf⟩ := List.exists_of_findSome?_eq_some hstep
  clear hstep
  by_cases hexp : e.any (· == sf) = true
  · simp only [hexp, if_true] at hsf
    exact absurd hsf (by simp)
  · rw [if_neg (by simpa using hexp)] at hsf
    refine ⟨sf, hsfmem, by simpa using hexp, ?_⟩
    clear hexp
    split at hsf <;> repeat' split at hsf
    all_goals try injection hsf
    all_goals (rename_i hsf; simp only [Prod.mk.injEq] at hsf)
    all_goals first
      | (refine Or.inl ⟨_, ?_, hsf.2.2.1.symm, hsf.1.symm, hsf.2.1.symm, ?_⟩
         · exact hkK _ _
             (blockingWorldS5Keyed_eq_birthContent φ₀ keys b _ _ sf.label _ (by assumption))
         · unfold isMintingShaped; simp_all)
      | (refine Or.inr ⟨?_, ?_⟩
         · rw [show modalApplyOneS5 sf b acc = _ from by assumption]
           exact hsf.2.2.1.symm
         · rw [show modalApplyOneS5 sf b acc = _ from by assumption]
           exact ⟨by simpa using hsf.1.symm, by simpa using hsf.2.1.symm⟩)

omit [Hashable Atom] in
/-- **Phase 4 field 1/6**: `modalStepBranchS5gKeyed` preserves `e.Nodup`. Rule-agnostic: the
new expanded set is always either `e ++ [sf]` (with `sf ∉ e` from the stepper's own dedup guard)
or `e` unchanged, across all three of the stepper's top-level cases. -/
lemma modalStepBranchS5g_preserves_eNodup (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (newBs newExps : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (newAcc : Accessibility) (newKeys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (hstep : modalStepBranchS5gKeyed φ₀ b e acc keys = some (newBs, newExps, newAcc, newKeys))
    (henodup : e.Nodup) :
    ∀ e' ∈ newExps, e'.Nodup := by
  obtain ⟨sf, -, hsfnotin, hshape⟩ :=
    modalStepBranchS5gKeyed_expanded_shape φ₀ b e acc keys newBs newExps newAcc newKeys hstep
  intro e' he'
  rcases hshape e' he' with rfl | rfl
  · rw [List.nodup_append]
    refine ⟨henodup, List.nodup_singleton sf, ?_⟩
    intro a ha y hy
    simp only [List.mem_singleton] at hy
    subst hy
    intro heq
    subst heq
    exact hsfnotin ha
  · exact henodup

/-- **Phase 4 field 2/6**: `modalStepBranchS5gKeyed` preserves `accFreshInv`. Blocked (loop-back)
steps add an edge to a *known* world (`S5LoopInv.keysKnown`), which is `< modalNextWorld b`
since every known world is some branch formula's label (`modalNextWorld_gt`); non-blocked steps
either leave `acc` unchanged (`modalNextWorld` only grows under branch prepend,
`modalNextWorld_le_append`) or mint a fresh edge to `modalNextWorld b` itself, which becomes
`< modalNextWorld b'` once `b'` contains the freshly-labeled witness formula
(`modalApplyOne_knownWorlds_step`'s mint disjunct, lifted to `modalApplyOneS5` via
`modalApplyOneS5_eq_of_linear`). -/
lemma modalStepBranchS5g_preserves_accFresh (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (newBs newExps : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (newAcc : Accessibility) (newKeys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (hstep : modalStepBranchS5gKeyed φ₀ b e acc keys = some (newBs, newExps, newAcc, newKeys))
    (hkK : ∀ w k, (w, k) ∈ keys → w ∈ modalKnownWorlds b)
    (hknown : accTargetsKnown b acc) (hfresh : accFreshInv b acc) :
    ∀ b' ∈ newBs, accFreshInv b' newAcc := by
  obtain ⟨sf, hsfmem, -, hcase⟩ :=
    modalStepBranchS5gKeyed_acc_shape φ₀ b e acc keys newBs newExps newAcc newKeys hstep hkK
  rcases hcase with ⟨wBlock, hwBlock, hnewAcc, hnewBs, -, -⟩ | ⟨hnewAcc, hshape⟩
  · subst hnewAcc
    intro b' hb'
    rw [hnewBs] at hb'
    simp only [List.mem_singleton] at hb'
    rw [hb']
    intro w w' hedge
    rcases hasEdge_addEdge_cases_S5 hedge with ⟨hw1, hw2⟩ | hold
    · rw [hw1, hw2]
      refine ⟨modalNextWorld_gt b sf hsfmem, ?_⟩
      obtain ⟨sfw, hsfw, hsfwl⟩ := (mem_modalKnownWorlds_S5 b wBlock).mp hwBlock
      exact hsfwl ▸ modalNextWorld_gt b sfw hsfw
    · exact hfresh w w' hold
  · have hbb' : ∀ b' ∈ newBs, ∃ xs, b' = xs ++ b := by
      intro b' hb'
      rcases hm : (modalApplyOneS5 sf b acc).fst with nf | brs | nf | -
      · rw [hm] at hshape; rw [hshape.1] at hb'
        simp only [List.mem_singleton] at hb'; exact ⟨nf, hb'⟩
      · rw [hm] at hshape; rw [hshape.1] at hb'
        obtain ⟨br, -, rfl⟩ := List.mem_map.mp hb'; exact ⟨br, rfl⟩
      · rw [hm] at hshape; rw [hshape.1] at hb'
        simp only [List.mem_singleton] at hb'; exact ⟨nf, hb'⟩
      · rw [hm] at hshape; exact absurd hshape (by simp)
    rcases modalApplyOne_knownWorlds_step sf b acc hsfmem hknown with
      ⟨hsndeq, -⟩ | ⟨hsndeq, hmatch⟩
    · rw [hnewAcc, modalApplyOneS5_snd_eq sf b acc, hsndeq]
      intro b' hb' w w' hedge
      obtain ⟨xs, rfl⟩ := hbb' b' hb'
      obtain ⟨hw, hw'⟩ := hfresh w w' hedge
      exact ⟨lt_of_lt_of_le hw (modalNextWorld_le_append xs b),
             lt_of_lt_of_le hw' (modalNextWorld_le_append xs b)⟩
    · rcases hkf : (modalApplyOne sf b acc).fst with formulas | brs | nf | -
      · rw [hkf] at hmatch
        obtain ⟨hne, hlabel⟩ := hmatch
        have heqS5 := modalApplyOneS5_eq_of_linear sf b acc formulas hkf
        rw [hnewAcc, modalApplyOneS5_snd_eq sf b acc, hsndeq]
        intro b' hb'
        have hfst : (modalApplyOneS5 sf b acc).fst = RuleResult.linear formulas := by
          rw [heqS5]; exact hkf
        rw [hfst] at hshape
        rw [hshape.1] at hb'
        simp only [List.mem_singleton] at hb'
        rw [hb']
        cases formulas with
        | nil => exact absurd rfl hne
        | cons x0 rest =>
          have hx0mem : x0 ∈ x0 :: rest := List.mem_cons_self
          have hx0label := hlabel x0 hx0mem
          have hx0memb' : x0 ∈ (x0 :: rest) ++ b := List.mem_append_left b hx0mem
          have hgrow : modalNextWorld b < modalNextWorld ((x0 :: rest) ++ b) := by
            have hh := modalNextWorld_gt ((x0 :: rest) ++ b) x0 hx0memb'
            rwa [hx0label] at hh
          intro w w' hedge
          rcases hasEdge_addEdge_cases_S5 hedge with ⟨rfl, rfl⟩ | hold
          · exact ⟨lt_trans (modalNextWorld_gt b sf hsfmem) hgrow, hgrow⟩
          · obtain ⟨hw, hw'⟩ := hfresh w w' hold
            exact ⟨lt_trans hw hgrow, lt_trans hw' hgrow⟩
      · rw [hkf] at hmatch; exact hmatch.elim
      · rw [hkf] at hmatch; exact hmatch.elim
      · rw [hkf] at hmatch; exact hmatch.elim

/-- **Phase 4 field 3/6**: `modalStepBranchS5gKeyed` preserves `accTargetsKnown`. Blocked
(loop-back) steps add an edge to a known world directly (`S5LoopInv.keysKnown`); non-blocked
steps either leave `acc` unchanged (old targets stay known since the branch only grows,
`modalKnownWorlds_mono_append_S5`) or mint a fresh edge to `modalNextWorld b`, immediately known
on the grown branch since it is the freshly-labeled witness formula's own label. -/
lemma modalStepBranchS5g_preserves_accKnown (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (newBs newExps : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (newAcc : Accessibility) (newKeys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (hstep : modalStepBranchS5gKeyed φ₀ b e acc keys = some (newBs, newExps, newAcc, newKeys))
    (hkK : ∀ w k, (w, k) ∈ keys → w ∈ modalKnownWorlds b)
    (hknown : accTargetsKnown b acc) :
    ∀ b' ∈ newBs, accTargetsKnown b' newAcc := by
  obtain ⟨sf, hsfmem, -, hcase⟩ :=
    modalStepBranchS5gKeyed_acc_shape φ₀ b e acc keys newBs newExps newAcc newKeys hstep hkK
  rcases hcase with ⟨wBlock, hwBlock, hnewAcc, hnewBs, -, -⟩ | ⟨hnewAcc, hshape⟩
  · subst hnewAcc
    intro b' hb'
    rw [hnewBs] at hb'
    simp only [List.mem_singleton] at hb'
    rw [hb']
    intro w w' hedge
    rcases hasEdge_addEdge_cases_S5 hedge with ⟨hw1, hw2⟩ | hold
    · rw [hw2]; exact hwBlock
    · exact hknown w w' hold
  · have hbb' : ∀ b' ∈ newBs, ∃ xs, b' = xs ++ b := by
      intro b' hb'
      rcases hm : (modalApplyOneS5 sf b acc).fst with nf | brs | nf | -
      · rw [hm] at hshape; rw [hshape.1] at hb'
        simp only [List.mem_singleton] at hb'; exact ⟨nf, hb'⟩
      · rw [hm] at hshape; rw [hshape.1] at hb'
        obtain ⟨br, -, rfl⟩ := List.mem_map.mp hb'; exact ⟨br, rfl⟩
      · rw [hm] at hshape; rw [hshape.1] at hb'
        simp only [List.mem_singleton] at hb'; exact ⟨nf, hb'⟩
      · rw [hm] at hshape; exact absurd hshape (by simp)
    rcases modalApplyOne_knownWorlds_step sf b acc hsfmem hknown with
      ⟨hsndeq, -⟩ | ⟨hsndeq, hmatch⟩
    · rw [hnewAcc, modalApplyOneS5_snd_eq sf b acc, hsndeq]
      intro b' hb' w w' hedge
      obtain ⟨xs, rfl⟩ := hbb' b' hb'
      exact modalKnownWorlds_mono_append_S5 xs b w' (hknown w w' hedge)
    · rcases hkf : (modalApplyOne sf b acc).fst with formulas | brs | nf | -
      · rw [hkf] at hmatch
        obtain ⟨hne, hlabel⟩ := hmatch
        have heqS5 := modalApplyOneS5_eq_of_linear sf b acc formulas hkf
        rw [hnewAcc, modalApplyOneS5_snd_eq sf b acc, hsndeq]
        intro b' hb'
        have hfst : (modalApplyOneS5 sf b acc).fst = RuleResult.linear formulas := by
          rw [heqS5]; exact hkf
        rw [hfst] at hshape
        rw [hshape.1] at hb'
        simp only [List.mem_singleton] at hb'
        rw [hb']
        cases formulas with
        | nil => exact absurd rfl hne
        | cons x0 rest =>
          have hx0mem : x0 ∈ x0 :: rest := List.mem_cons_self
          have hx0label := hlabel x0 hx0mem
          have hx0memb' : x0 ∈ (x0 :: rest) ++ b := List.mem_append_left b hx0mem
          have hfreshknown : modalNextWorld b ∈ modalKnownWorlds ((x0 :: rest) ++ b) :=
            (mem_modalKnownWorlds_S5 _ _).mpr ⟨x0, hx0memb', hx0label⟩
          intro w w' hedge
          rcases hasEdge_addEdge_cases_S5 hedge with ⟨hw1, hw2⟩ | hold
          · rw [hw2]; exact hfreshknown
          · exact modalKnownWorlds_mono_append_S5 (x0 :: rest) b w' (hknown w w' hold)
      · rw [hkf] at hmatch; exact hmatch.elim
      · rw [hkf] at hmatch; exact hmatch.elim
      · rw [hkf] at hmatch; exact hmatch.elim

omit [Hashable Atom] in
/-- **Phase 4 field 4/6**: `modalStepBranchS5gKeyed` preserves the `outDeg`/expanded-set
minting-count correspondence. Blocked (loop-back) steps add an edge at the (minting-shaped)
trigger's own label, exactly matching the appended `[sf]` in the new expanded set
(`outDeg_addEdge_self`/`filter_minting_append_of_minting_at`); non-blocked steps reduce to K's
own per-call counting obligation (`modalApplyOne_outDeg_step`), whose `e`-growth/unchanged
dichotomy agrees with `modalStepBranchS5gKeyed`'s own (`modalApplyOneS5_eshape_eq`). -/
lemma modalStepBranchS5g_preserves_outDegEq (φ₀ : Proposition Atom)
    (b e : List (SignedFormula (Proposition Atom) WorldIndex)) (acc : Accessibility)
    (keys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (newBs newExps : List (List (SignedFormula (Proposition Atom) WorldIndex)))
    (newAcc : Accessibility) (newKeys : List (WorldIndex × Finset (Sign × Proposition Atom)))
    (hstep : modalStepBranchS5gKeyed φ₀ b e acc keys = some (newBs, newExps, newAcc, newKeys))
    (hkK : ∀ w k, (w, k) ∈ keys → w ∈ modalKnownWorlds b)
    (houtdeg :
      ∀ w, outDeg acc w = (e.filter (fun x => x.label == w && isMintingShaped x)).length) :
    ∀ e' ∈ newExps, ∀ w, outDeg newAcc w =
      (e'.filter (fun x => x.label == w && isMintingShaped x)).length := by
  obtain ⟨sf, hsfmem, -, hcase⟩ :=
    modalStepBranchS5gKeyed_acc_shape φ₀ b e acc keys newBs newExps newAcc newKeys hstep hkK
  rcases hcase with ⟨wBlock, -, hnewAcc, -, hnewExps, hmint⟩ | ⟨hnewAcc, hshape⟩
  · subst hnewAcc
    intro e' he'
    rw [hnewExps] at he'
    simp only [List.mem_singleton] at he'
    subst he'
    intro w
    by_cases hw : w = sf.label
    · subst hw
      rw [outDeg_addEdge_self_S5, filter_minting_append_of_minting_at_S5 e sf hmint,
        houtdeg sf.label]
      simp
    · rw [outDeg_addEdge_ne_S5 acc sf.label wBlock w hw,
        filter_minting_append_of_minting_ne_S5 e sf w hw, houtdeg w]
  · rw [hnewAcc, modalApplyOneS5_snd_eq sf b acc]
    intro e' he' w
    have hfull : outDeg (modalApplyOne sf b acc).2 w =
        (List.filter (fun x => x.label == w && isMintingShaped x)
          (match (modalApplyOneS5 sf b acc).fst with
            | .linear _ => e ++ [sf]
            | .branching _ => e ++ [sf]
            | .persistent _ => e
            | .notApplicable => e)).length :=
      (modalApplyOne_outDeg_step sf b e acc houtdeg w).trans
        (congrArg (fun l => (List.filter (fun x => x.label == w && isMintingShaped x) l).length)
          (modalApplyOneS5_eshape_eq sf b e acc).symm)
    rw [hfull]
    rcases hm : (modalApplyOneS5 sf b acc).fst with nf | brs | nf | -
    · rw [hm] at hshape
      rw [hshape.2] at he'
      simp only [List.mem_singleton] at he'
      subst he'
      rfl
    · rw [hm] at hshape
      rw [hshape.2] at he'
      obtain ⟨br, -, rfl⟩ := List.mem_map.mp he'
      rfl
    · rw [hm] at hshape
      rw [hshape.2] at he'
      simp only [List.mem_singleton] at he'
      subst he'
      rfl
    · rw [hm] at hshape; exact hshape.elim

/-! ## Phase 2 Obstruction: `RuleApplicationSpec.rankStep` Is Not Dischargeable

**[BLOCKED]** (Phase 2). Attempting to discharge `RuleApplicationSpec modalApplyOneS5`
(mirroring `modalApplyOneB_spec`, `BDriver.lean`) fails at the `rankStep` field
(`GenericDriver.lean`). This section records a fully mechanized, sorry-free counterexample
proving the field is **mathematically false** for `modalApplyOneS5`, not merely unproved.

**Root cause.** `rankStep` requires: given *any* `rank : WorldIndex → Nat` satisfying the
depth-bound invariant `∀ x ∈ b, modalDepth x.formula ≤ rank x.label` and the edge-decrement
invariant `∀ w w', acc.hasEdge w w' → rank w' + 1 = rank w` (the bookkeeping the K-style FMP
potential argument threads through the whole branch), the rule's *new* output formulas must
again satisfy the depth bound at their (possibly-`rank'`-updated) labels. For T's self
propagation (target = the trigger's own world `w`) and B's backward propagation (target = a
*recorded-edge* predecessor of `w`, so `hedge` directly relates `rank v` to `rank w`), this
holds because the target world's rank is provably related to the trigger world's rank via
`hedge`. **S5's universal propagation targets `modalKnownWorlds b` unconditionally** -- a known
world `v` need not have *any* recorded-edge relationship to the trigger world `w` (e.g. `v` may
sit in an unrelated subtree, deeper in the tableau's mint-tree than `w`'s own rank budget
allows) -- so no such relation between `rank v` and `rank w` exists in general, and `rankStep`'s
conclusion can fail.

**Mechanized counterexample.** Instantiate `Atom := Nat`, `φtest := ◇◇(atom 0)` (so
`modalDepth φtest = 2`, `modalDepth (□φtest) = 3`), `sf0 := T(□φtest)@0`, `sf3 := T(atom 0)@3`,
`btest := [sf0, sf3]`, and `acctest` the four-world chain `0 → 1 → 2 → 3`. The tight rank map
`rankTest w := 3 - w` satisfies both `rankStep` hypotheses (`hbound`, `hedge`) at
`(sf0, btest, acctest)` -- confirmed below -- yet `modalApplyOneS5 sf0 btest acctest` (computed
by `rfl`, since every ingredient is a closed, decidable, fully-applied term) emits
`T(φtest)@3` via the universal rule (world `3` is a known world of `btest`), while
`modalDepth φtest = 2 > rankTest 3 = 0`. Since `3 ≠ modalNextWorld btest` (`= 4`), **any**
`rank'` satisfying `rankStep`'s own "agrees with `rank` off the fresh point" clause is *forced*
to have `rank' 3 = rankTest 3 = 0`, so no valid `rank'` can satisfy the field's conclusion. -/

section RankStepObstruction

/-- The test formula `◇◇(atom 0)` (`modalDepth = 2`) used by the `rankStep` counterexample
below: its boxed form `□◇◇(atom 0)` (`modalDepth = 3`) is the trigger for `modalApplyOneS5`'s
universal propagation. -/
def s5RankCounterFormula : Proposition Nat := .diamond (.diamond (.atom 0))

/-- The counterexample's triggering signed formula `T(□s5RankCounterFormula)@0`. -/
def s5RankCounterSf0 : SignedFormula (Proposition Nat) WorldIndex :=
  ⟨.pos, .box s5RankCounterFormula, 0⟩

/-- A second branch member `T(atom 0)@3` witnessing that world `3` is a known world of the
counterexample branch (so the universal rule targets it). -/
def s5RankCounterSf3 : SignedFormula (Proposition Nat) WorldIndex :=
  ⟨.pos, .atom 0, 3⟩

/-- The counterexample branch `[s5RankCounterSf0, s5RankCounterSf3]`. -/
def s5RankCounterBranch : List (SignedFormula (Proposition Nat) WorldIndex) :=
  [s5RankCounterSf0, s5RankCounterSf3]

/-- The counterexample's accessibility relation: the four-world chain `0 → 1 → 2 → 3`. -/
def s5RankCounterAcc : Accessibility :=
  ((Accessibility.empty.addEdge 0 1).addEdge 1 2).addEdge 2 3

/-- The tight rank map `rank w := 3 - w`, satisfying `rankStep`'s `hbound`/`hedge` hypotheses at
the counterexample instantiation (see `s5RankCounter_hbound`/`s5RankCounter_hedge` below). -/
def s5RankCounterRank : WorldIndex → Nat := fun w => 3 - w

lemma s5RankCounter_sf0_mem : s5RankCounterSf0 ∈ s5RankCounterBranch := by decide

lemma s5RankCounter_accFreshInv :
    accFreshInv s5RankCounterBranch s5RankCounterAcc := by
  intro w w' hedge
  simp only [s5RankCounterAcc, Accessibility.addEdge, Accessibility.hasEdge,
    Accessibility.empty, List.any_cons, List.any_nil, Bool.or_eq_true, Bool.and_eq_true,
    beq_iff_eq] at hedge
  rcases hedge with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | hf <;>
    simp_all [modalNextWorld, modalMaxWorld, s5RankCounterBranch, s5RankCounterSf0,
      s5RankCounterSf3, List.foldl]

lemma s5RankCounter_hbound :
    ∀ x ∈ s5RankCounterBranch, modalDepth x.formula ≤ s5RankCounterRank x.label := by
  intro x hx
  simp only [s5RankCounterBranch, List.mem_cons, List.not_mem_nil, or_false] at hx
  rcases hx with rfl | rfl <;>
    simp [s5RankCounterSf0, s5RankCounterSf3, s5RankCounterFormula, modalDepth,
      s5RankCounterRank]

lemma s5RankCounter_hedge :
    ∀ w w', s5RankCounterAcc.hasEdge w w' → s5RankCounterRank w' + 1 = s5RankCounterRank w := by
  intro w w' hedge
  simp only [s5RankCounterAcc, Accessibility.addEdge, Accessibility.hasEdge,
    Accessibility.empty, List.any_cons, List.any_nil, Bool.or_eq_true, Bool.and_eq_true,
    beq_iff_eq] at hedge
  rcases hedge with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | hf <;> simp_all [s5RankCounterRank]

lemma s5RankCounter_fst :
    (modalApplyOneS5 s5RankCounterSf0 s5RankCounterBranch s5RankCounterAcc).fst =
      RuleResult.persistent
        [⟨.pos, s5RankCounterFormula, 1⟩, ⟨.pos, s5RankCounterFormula, 3⟩,
          ⟨.pos, s5RankCounterFormula, 0⟩] := by rfl

lemma s5RankCounter_three_ne_next :
    (3 : WorldIndex) ≠ modalNextWorld s5RankCounterBranch := by decide

/-- **The mechanized counterexample**: `RuleApplicationSpec.rankStep` (`GenericDriver.lean`)
fails for `modalApplyOneS5` at this concrete, fully-decidable instantiation. No valid `rank'`
exists satisfying all three conjuncts of the field's conclusion, because any such `rank'` is
forced to agree with `s5RankCounterRank` at world `3` (`≠ modalNextWorld s5RankCounterBranch`),
and `s5RankCounterFormula`'s depth (`2`) exceeds `s5RankCounterRank 3` (`0`) while
`T(s5RankCounterFormula)@3` is a genuine member of the rule's persistent output. This is the
formal record of Phase 2's `[BLOCKED]` status: the universal "propagate to every known world"
S5 rule cannot be discharged against the K-style FMP `rank`-potential machinery
`RuleApplicationSpec` presupposes, for the same underlying reason `S4`'s transitive 4-rule
cannot (`GenericDriver.lean`'s module docstring, "S4 is explicitly NOT an instance"): both
propagate content to worlds whose depth-budget is not controlled by any recorded edge to the
trigger world. -/
theorem modalApplyOneS5_rankStep_not_dischargeable :
    ¬ ∃ rank' : WorldIndex → Nat,
        (∀ w, w ≠ modalNextWorld s5RankCounterBranch → rank' w = s5RankCounterRank w) ∧
        (∀ w w', (modalApplyOneS5 s5RankCounterSf0 s5RankCounterBranch
              s5RankCounterAcc).snd.hasEdge w w' → rank' w' + 1 = rank' w) ∧
        (match (modalApplyOneS5 s5RankCounterSf0 s5RankCounterBranch
              s5RankCounterAcc).fst with
          | .linear formulas => ∀ x ∈ formulas, modalDepth x.formula ≤ rank' x.label
          | .branching branches => ∀ x ∈ branches.flatten, modalDepth x.formula ≤ rank' x.label
          | .persistent formulas => ∀ x ∈ formulas, modalDepth x.formula ≤ rank' x.label
          | .notApplicable => True) := by
  rintro ⟨rank', hagree, -, hmatch⟩
  rw [s5RankCounter_fst] at hmatch
  simp only at hmatch
  have h3 : modalDepth s5RankCounterFormula ≤ rank' 3 :=
    hmatch ⟨.pos, s5RankCounterFormula, 3⟩ (by simp)
  have hagree3 : rank' 3 = s5RankCounterRank 3 := hagree 3 s5RankCounter_three_ne_next
  rw [hagree3] at h3
  simp only [s5RankCounterFormula, modalDepth, s5RankCounterRank] at h3
  omega

end RankStepObstruction

/-! ## Scope Note: Pure-K5 / Pure-5 Is Out of Scope

This file delivers S5 (equivalence-frame) coverage, and — for the parts independent of the
blocked `Phase 2 Obstruction` above (`extractModelS5` and its `RightEuclidean` exposure,
`FrameCompleteness.lean`) — 5/KB5 coverage **via the S5/equivalence route**: every equivalence
relation is `Relation.RightEuclidean` (`Relation.symm_rightEuclidean_iff_trans`,
`Cslib/Foundations/Relation/Euclidean.lean`), so a countermodel extracted as an equivalence
closure (`Relation.EqvGen`) automatically satisfies the Euclidean frame condition "for free".

Genuine **pure-K5 / pure-5** completeness — Euclidean accessibility *without* assuming full
equivalence (i.e. Euclidean plus, for KB5, seriality, but *not* reflexivity/transitivity/symmetry
as freestanding properties) — is explicitly **OUT OF SCOPE** for this file. Mathlib ships no
closure operator that produces a Euclidean-but-not-necessarily-equivalence relation from a set of
tableau edges (unlike `Relation.SymmGen`/`Relation.EqvGen`, which the B/S5 routes reuse
directly), so building a genuine pure-K5 countermodel extractor would require inventing a new,
bespoke closure (e.g. a hypothetical `EuclGen`) and re-deriving its properties from scratch — a
separate, self-contained piece of work, not an instantiation of the existing generic driver.
This is deferred to a dedicated `pure-k5-euclidean-closure` follow-up task, per the parent plan's
non-goals (`reports/03_parent-phase-plan-reference.md`). Do **not** introduce a custom `EuclGen`
closure operator in this file. -/

end Cslib.Logic.Modal.Tableau

end
