/-
Copyright (c) 2026 Benjamin Brast-McKie. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Benjamin Brast-McKie
-/

module
public import Cslib.Logics.Modal.Basic
public import Cslib.Foundations.Logic.Axioms
public import Mathlib.Data.Finset.Basic

/-! # Schema-Union Axiom Combinator for Modal Proof Systems

This module introduces a compositional replacement for the 15 hand-written per-system modal
axiom inductives (`KAxiom`, `TAxiom`, …, and S5's `ModalAxiom`) in
`Cslib.Logics.Modal.ProofSystem.Instances` / `Cslib.Logics.Modal.Metalogic.DerivationTree`.
Those 15 predicates each re-list a byte-identical 13-constructor propositional + K +
diamond-duality core and differ only in a subset of 5 modal-strength schemata
(`modalT/D/B/Four/Five`), forming a clean 18-tag alphabet.

This is purely additive scaffolding (Phase 1 of the schema-union rollout): it depends only on
the `Proposition`/axiom-schema layer (`Modal.Basic`, `Foundations.Logic.Axioms`) and touches no
system-specific file. Nothing downstream is changed by landing this file.

## Key Components

- `ModalSchemaTag`: the 18-tag alphabet of shared modal axiom schemata.
- `ModalSchemaTag.Holds`: the formula-level meaning of each tag, as an existential over the
  schema's metavariables (the "schema = set of its instances" encoding).
- `SchemaUnion`: the axiom predicate generated by a chosen `Finset` of tags.
- `SchemaUnion.subsumption`: the single generic subsumption lemma — enlarging the tag set only
  weakens the resulting predicate. Downstream `XAxiom_implies_YAxiom` lemmas (Phase 5) become
  `Finset.subset` facts discharged through this one lemma.

## Design Invariants

- `.Holds` keeps the existential-over-metavariables form (`∃ φ ψ, χ = …`), matching each
  existing `<Sys>Axiom` constructor's proposition shape so that the future bridge equivalences
  `SchemaUnion sysTags φ ↔ <Sys>Axiom φ` hold.
- The tag collection is a `Finset` (not a `Set`): the 18-tag alphabet is finite, so `Finset`
  gives `DecidableEq`, decidable membership, and the subsumption lattice for free.
- `ModalSchemaTag` / `SchemaUnion` stay free of classical-only assumptions: the
  intuitionistic/minimal axiom families are a possible future instance of this same
  abstraction, not generalized to cover them here (out of scope for this task).
-/

@[expose] public section

open Cslib.Logic

namespace Cslib.Logic.Modal

variable {Atom : Type u}

/-! ## Schema Tag Alphabet -/

/-- The 18 shared modal axiom schema tags. Every one of the 15 classical normal modal systems
(`K`, `T`, `D`, `KB`, `K4`, `K5`, `K45`, `S4`, `S5`, `TB`, `KB5`, `D4`, `D5`, `D45`, `DB`) is the
union of the 13-tag propositional + K + and/or + diamond-duality core (`implyK`, `implyS`,
`efq`, `peirce`, `modalK`, `andI`, `andE1`, `andE2`, `orI1`, `orI2`, `orE`, `diaDualityFwd`,
`diaDualityBack`) with a subset of the 5 modal-strength differentiator tags (`modalT`, `modalD`,
`modalB`, `modalFour`, `modalFive`). -/
inductive ModalSchemaTag
  /-- Weakening: `φ → (ψ → φ)`. -/
  | implyK
  /-- Distribution: `(φ → (ψ → χ)) → ((φ → ψ) → (φ → χ))`. -/
  | implyS
  /-- Ex falso quodlibet: `⊥ → φ`. -/
  | efq
  /-- Peirce's law / DNE: `((φ → ψ) → φ) → φ`. -/
  | peirce
  /-- K distribution: `□(φ → ψ) → (□φ → □ψ)`. -/
  | modalK
  /-- T / reflexivity: `□φ → φ`. -/
  | modalT
  /-- D / seriality: `□φ → ◇φ`. -/
  | modalD
  /-- B / symmetry: `φ → □◇φ`. -/
  | modalB
  /-- 4 / transitivity: `□φ → □□φ`. -/
  | modalFour
  /-- 5 / Euclideanness: `◇φ → □◇φ`. -/
  | modalFive
  /-- Conjunction introduction: `φ → (ψ → φ ∧ ψ)`. -/
  | andI
  /-- Left conjunction elimination: `φ ∧ ψ → φ`. -/
  | andE1
  /-- Right conjunction elimination: `φ ∧ ψ → ψ`. -/
  | andE2
  /-- Left disjunction introduction: `φ → φ ∨ ψ`. -/
  | orI1
  /-- Right disjunction introduction: `ψ → φ ∨ ψ`. -/
  | orI2
  /-- Disjunction elimination: `(φ → χ) → ((ψ → χ) → ((φ ∨ ψ) → χ))`. -/
  | orE
  /-- Diamond duality, forward direction: `◇φ → ¬□¬φ`. -/
  | diaDualityFwd
  /-- Diamond duality, backward direction: `¬□¬φ → ◇φ`. -/
  | diaDualityBack
  deriving DecidableEq

/-! ## Formula-Level Meaning -/

/-- Formula-level meaning of each schema tag, as an existential over the schema's metavariables
(the "schema = set of its instances" encoding, design invariant 3 of the schema-union rollout).

Each clause's proposition shape matches, byte-for-byte, the corresponding constructor of the
pre-existing per-system axiom inductives (`Cslib.Logics.Modal.ProofSystem.Instances.KAxiom`
and its 13 siblings, plus S5's `ModalAxiom` in `Cslib.Logics.Modal.Metalogic.DerivationTree`),
so that the future bridge equivalences `SchemaUnion sysTags φ ↔ <Sys>Axiom φ` hold. -/
def ModalSchemaTag.Holds : ModalSchemaTag → Proposition Atom → Prop
  | .implyK, χ => ∃ φ ψ : Proposition Atom, χ = φ.imp (ψ.imp φ)
  | .implyS, χ => ∃ φ ψ ρ : Proposition Atom, χ = (φ.imp (ψ.imp ρ)).imp ((φ.imp ψ).imp (φ.imp ρ))
  | .efq, χ => ∃ φ : Proposition Atom, χ = Proposition.bot.imp φ
  | .peirce, χ => ∃ φ ψ : Proposition Atom, χ = ((φ.imp ψ).imp φ).imp φ
  | .modalK, χ => ∃ φ ψ : Proposition Atom, χ = (Proposition.box (φ.imp ψ)).imp
      ((Proposition.box φ).imp (Proposition.box ψ))
  | .modalT, χ => ∃ φ : Proposition Atom, χ = (Proposition.box φ).imp φ
  | .modalD, χ => ∃ φ : Proposition Atom, χ = (Proposition.box φ).imp
      ((Proposition.box (φ.imp Proposition.bot)).imp Proposition.bot)
  | .modalB, χ => ∃ φ : Proposition Atom, χ = Axioms.AxiomB φ
  | .modalFour, χ => ∃ φ : Proposition Atom,
      χ = (Proposition.box φ).imp (Proposition.box (Proposition.box φ))
  | .modalFive, χ => ∃ φ : Proposition Atom,
      χ = (((Proposition.box (φ.imp Proposition.bot)).imp Proposition.bot).imp
        (Proposition.box ((Proposition.box (φ.imp Proposition.bot)).imp Proposition.bot)))
  | .andI, χ => ∃ φ ψ : Proposition Atom, χ = Axioms.AndI φ ψ
  | .andE1, χ => ∃ φ ψ : Proposition Atom, χ = Axioms.AndE1 φ ψ
  | .andE2, χ => ∃ φ ψ : Proposition Atom, χ = Axioms.AndE2 φ ψ
  | .orI1, χ => ∃ φ ψ : Proposition Atom, χ = Axioms.OrI1 φ ψ
  | .orI2, χ => ∃ φ ψ : Proposition Atom, χ = Axioms.OrI2 φ ψ
  | .orE, χ => ∃ φ ψ ρ : Proposition Atom, χ = Axioms.OrE φ ψ ρ
  | .diaDualityFwd, χ => ∃ φ : Proposition Atom, χ = Axioms.AxiomDiaDualityFwd φ
  | .diaDualityBack, χ => ∃ φ : Proposition Atom, χ = Axioms.AxiomDiaDualityBack φ

/-! ## Schema-Union Combinator -/

/-- The schema-union combinator: the axiom predicate generated by a chosen `Finset` of schema
tags. `SchemaUnion S χ` holds iff `χ` is an instance of some tag in `S`. Each `<Sys>Axiom`
predicate becomes (in Phase 3) a one-line `SchemaUnion` declaration over that system's tag
set. -/
def SchemaUnion (S : Finset ModalSchemaTag) : Proposition Atom → Prop :=
  fun χ => ∃ t ∈ S, t.Holds χ

/-! ## Generic Subsumption -/

/-- Generic subsumption: enlarging the tag set only weakens the resulting `SchemaUnion`
predicate. This is the single generic lemma through which every `XAxiom_implies_YAxiom`
subsumption fact (Phase 5) is discharged as a `Finset.subset` fact — the modal cube is
literally the `⊆`-order on per-system tag sets (design invariant 1). -/
theorem SchemaUnion.subsumption {Sa Sb : Finset ModalSchemaTag} (hsub : Sa ⊆ Sb)
    {φ : Proposition Atom} (h : SchemaUnion Sa φ) : SchemaUnion Sb φ := by
  obtain ⟨t, ht, hφ⟩ := h
  exact ⟨t, hsub ht, hφ⟩

end Cslib.Logic.Modal
