module  -- shake: keep-all --deprecated_module: ignore

public import CslibTests.AncestorRedirectRefutation
public import CslibTests.BetaSplitRefutation
public import CslibTests.Bisimulation
public import CslibTests.CCS
public import CslibTests.CLL
public import CslibTests.ContextDecidability
public import CslibTests.DFA
public import CslibTests.FreeMonad
public import CslibTests.GrindLint
public import CslibTests.HML
public import CslibTests.HasFresh
public import CslibTests.HasSubstitution
public import CslibTests.HasWellFormed
public import CslibTests.HilbertSearch
public import CslibTests.HvalidShapeRefutation
public import CslibTests.ImportWithMathlib
public import CslibTests.LTS
public import CslibTests.LambdaCalculus
public import CslibTests.MLL
public import CslibTests.MinProbe
public import CslibTests.ModalFrameSeparation
public import CslibTests.MvalidBotShapeRefutation
public import CslibTests.OperatorPrecedenceRegression
public import CslibTests.Propositional
public import CslibTests.Reduction
public import CslibTests.S4LoopGuardRegression
public import CslibTests.TableauConformance
public import CslibTests.WitnessProbe
public import CslibTests.WitnessSearch3
