/-
Copyright (c) 2026 Benjamin Brast-McKie. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Benjamin Brast-McKie
-/

module

import Cslib.Init
import Mathlib.Tactic.Attr.Core

public import Mathlib.Data.SetLike.Basic
public import Mathlib.Data.Set.Lattice
public import Mathlib.Order.CompleteLattice.Defs
public import Cslib.Foundations.Order.HilbertAlgebra
public import Cslib.Logics.Propositional.Semantics.Algebra.FragmentPredicates
public import Cslib.Logics.Propositional.Semantics.Algebra.Hilbert

/-! # Diego Embedding Theorem

The **Diego embedding theorem** (Diego 1966; Rasiowa 1974, Ch. V) states that every Hilbert
algebra embeds into a Heyting algebra preserving the implication operation.

## Construction

Given a Hilbert algebra `(H, ⇨, ⊤)`, we construct:

1. **`HilbertFilter H`**: The type of *deductive filters* of `H` — nonempty upsets closed
   under modus ponens. Ordered by **set inclusion**: `F ≤ G ↔ F.carrier ⊆ G.carrier`.

2. **`CompleteLattice (HilbertFilter H)`**: Arbitrary intersections of deductive filters are
   deductive filters, giving a complete lattice with `sInf = intersection`.

3. **`GeneralizedHeytingAlgebra (HilbertFilter H)`**: The Heyting implication is
   `(F ⇨ G).carrier = {a | ∀ x, a ≤ x → x ∈ F → x ∈ G}`.
   The adjunction `K ⊓ F ≤ G ↔ K ≤ F ⇨ G` holds by the upset property and is proved using
   the K and S axioms for the MP-closure of `himpFilter`.

4. **`HilbertFilter.principal`**: The map `a ↦ {x | a ≤ x}` is injective and satisfies
   `principal(a ⇨ b) ≤ himpFilter (principal a) (principal b)` (the "embedding inequality").
   Full equality is not claimed here since the principal filter map is order-reversing in the
   inclusion-order lattice.

## Main Results

- `HilbertFilter.instGeneralizedHeytingAlgebra`: the filter lattice is a GHA.
- `HilbertFilter.principal_top`: `principal ⊤ = ⊥` (the principal filter of top is the bottom).
- `HilbertFilter.principal_injective`: The principal filter map is injective.
- `HilbertFilter.principal_le_himp`: `principal (a ⇨ b) ≤ principal a ⇨ principal b`.
- `hilbertEmbeddingLemma`: `HilbertEvaluate v φ = ⊤` iff the principal filter of the
  evaluation is the bottom of the filter lattice (holds for all formulas, primarily
  applied to `IsImpTopOnly` formulas in the Diego embedding context).

## References

* [A. Diego, *Sobre Algebras de Hilbert*][Diego1966]
* [A. Rasiowa, *An Algebraic Approach to Non-Classical Logics*][Rasiowa1974]
-/

@[expose] public section

namespace HilbertAlgebra

open HilbertAlgebra

/-! ## Phase 1: HilbertFilter Structure and Prerequisites -/

/-- A **deductive filter** (or Hilbert filter) of a Hilbert algebra `H` is a nonempty,
upward-closed subset of `H` that is closed under modus ponens.

- `top_mem`: the top element belongs to the filter
- `upper`: the filter is upward-closed under the algebra's partial order
- `mp`: the filter is closed under modus ponens

References: [Rasiowa1974], Definition V.3.1. -/
structure HilbertFilter (H : Type*) [HilbertAlgebra H] where
  /-- The underlying set of elements in the filter. -/
  carrier : Set H
  /-- The top element belongs to the filter. -/
  top_mem : ⊤ ∈ carrier
  /-- The filter is upward-closed. -/
  upper : ∀ {a b : H}, a ∈ carrier → a ≤ b → b ∈ carrier
  /-- The filter is closed under modus ponens. -/
  mp : ∀ {a b : H}, a ∈ carrier → (a ⇨ b) ∈ carrier → b ∈ carrier

namespace HilbertFilter

variable {H : Type*} [HilbertAlgebra H]

/-! ### SetLike and partial order -/

instance instSetLike : SetLike (HilbertFilter H) H where
  coe F := F.carrier
  coe_injective F G h := by cases F; cases G; congr

@[simp]
theorem mem_carrier {F : HilbertFilter H} {a : H} : a ∈ F.carrier ↔ a ∈ F := Iff.rfl

theorem top_mem_filter (F : HilbertFilter H) : (⊤ : H) ∈ F := F.top_mem
theorem upper_filter (F : HilbertFilter H) {a b : H} (ha : a ∈ F) (h : a ≤ b) : b ∈ F :=
  F.upper ha h
theorem mp_filter (F : HilbertFilter H) {a b : H} (ha : a ∈ F) (hab : (a ⇨ b) ∈ F) : b ∈ F :=
  F.mp ha hab

@[ext]
theorem ext {F G : HilbertFilter H} (h : ∀ a, a ∈ F ↔ a ∈ G) : F = G := SetLike.ext h

/-- Filters ordered by set inclusion: `F ≤ G ↔ F.carrier ⊆ G.carrier`. -/
instance instPartialOrder : PartialOrder (HilbertFilter H) where
  le F G := ∀ a, a ∈ F → a ∈ G
  le_refl _ _ ha := ha
  le_antisymm F G hFG hGF := ext (fun a => ⟨hFG a, hGF a⟩)
  le_trans _ _ _ hFG hGK a ha := hGK a (hFG a ha)

theorem le_iff {F G : HilbertFilter H} : F ≤ G ↔ ∀ a, a ∈ F → a ∈ G := Iff.rfl

/-! ### Principal filter -/

/-- The principal filter generated by `a : H` is `{x | a ≤ x}`, i.e., the set of elements
above `a`. This is the smallest deductive filter containing `a`. -/
def principal (a : H) : HilbertFilter H where
  carrier := {x | a ≤ x}
  top_mem := Set.mem_ofPred.mpr le_top
  upper ha hab := Set.mem_ofPred.mpr (le_trans (Set.mem_ofPred.mp ha) hab)
  mp {x y} ha hab := Set.mem_ofPred.mpr
    (himp_mp (himp_mp (himp_S a x y) (Set.mem_ofPred.mp hab)) (Set.mem_ofPred.mp ha))

@[simp]
theorem mem_principal {a x : H} : x ∈ principal a ↔ a ≤ x :=
  Set.mem_ofPred


/-- `principal a ≤ principal b ↔ b ≤ a` (the map is order-reversing). -/
theorem principal_le_iff {a b : H} : principal a ≤ principal b ↔ b ≤ a := by
  simp only [le_iff, mem_principal]
  exact ⟨fun h => h a le_rfl, fun h x hax => le_trans h hax⟩


/-- The principal filter map is injective. -/
theorem principal_injective : Function.Injective (principal (H := H)) := by
  intro a b h
  have ha : a ≤ b := by
    have := @principal_le_iff H _ b a
    rw [h] at this
    exact this.mp le_rfl
  have hb : b ≤ a := by
    have := @principal_le_iff H _ a b
    rw [h] at this
    exact this.mp le_rfl
  exact le_antisymm ha hb

/-! ## Phase 2: CompleteLattice and GeneralizedHeytingAlgebra -/

/-! ### Intersection (sInf) of deductive filters -/

/-- The intersection of two deductive filters is a deductive filter. -/
def infFilter (F G : HilbertFilter H) : HilbertFilter H where
  carrier := F.carrier ∩ G.carrier
  top_mem := ⟨F.top_mem, G.top_mem⟩
  upper ha hab := ⟨F.upper ha.1 hab, G.upper ha.2 hab⟩
  mp ha hab := ⟨F.mp ha.1 hab.1, G.mp ha.2 hab.2⟩

@[simp]
theorem mem_infFilter {F G : HilbertFilter H} {a : H} :
    a ∈ infFilter F G ↔ a ∈ F ∧ a ∈ G := Iff.rfl

private theorem infFilter_le_left (F G : HilbertFilter H) : infFilter F G ≤ F :=
  fun _ ha => ha.1

private theorem infFilter_le_right (F G : HilbertFilter H) : infFilter F G ≤ G :=
  fun _ ha => ha.2

private theorem le_infFilter (K F G : HilbertFilter H) (hKF : K ≤ F) (hKG : K ≤ G) :
    K ≤ infFilter F G :=
  fun a ha => ⟨hKF a ha, hKG a ha⟩

/-- The intersection of an arbitrary family of deductive filters is a deductive filter. -/
def sInfFilter (S : Set (HilbertFilter H)) : HilbertFilter H where
  carrier := ⋂ F ∈ S, (F : Set H)
  top_mem := by simp only [Set.mem_iInter]; intro F hFS; exact F.top_mem
  upper ha hab := by
    simp only [Set.mem_iInter] at ha ⊢
    exact fun F hFS => F.upper (ha F hFS) hab
  mp ha hab := by
    simp only [Set.mem_iInter] at ha hab ⊢
    exact fun F hFS => F.mp (ha F hFS) (hab F hFS)

@[simp]
theorem mem_sInfFilter {S : Set (HilbertFilter H)} {a : H} :
    a ∈ sInfFilter S ↔ ∀ F ∈ S, a ∈ F :=
  ⟨fun h F hF => Set.mem_iInter₂.mp h F hF, fun h => Set.mem_iInter₂.mpr fun F hF => h F hF⟩

/-- The whole set `H` is a deductive filter (the top of the inclusion order). -/
def topFilter : HilbertFilter H where
  carrier := Set.univ
  top_mem := Set.mem_univ _
  upper _ _ := Set.mem_univ _
  mp _ _ := Set.mem_univ _

instance instOrderTop : OrderTop (HilbertFilter H) where
  top := topFilter
  le_top _ _ _ := Set.mem_univ _

instance instInfSet : InfSet (HilbertFilter H) where
  sInf S := sInfFilter S

@[simp]
theorem mem_sInf {S : Set (HilbertFilter H)} {a : H} :
    a ∈ sInf S ↔ ∀ F ∈ S, a ∈ F := mem_sInfFilter

instance instSupSet : SupSet (HilbertFilter H) where
  sSup S := sInf {G | ∀ F ∈ S, F ≤ G}

@[simp]
theorem mem_sSup {S : Set (HilbertFilter H)} {a : H} :
    a ∈ sSup S ↔ ∀ G : HilbertFilter H, (∀ F ∈ S, F ≤ G) → a ∈ G := by
  simp [sSup, sInf, mem_sInfFilter, le_iff]

/-- The filter lattice with the inclusion order is a complete lattice,
with `sInf = intersection of carriers`. -/
instance instCompleteLattice : CompleteLattice (HilbertFilter H) :=
  completeLatticeOfInf (HilbertFilter H) (fun S => by
    constructor
    · -- sInf S is a lower bound: sInf S ≤ F for each F ∈ S
      intro F hFS
      rw [le_iff]
      intro a ha
      rw [mem_sInf] at ha
      exact ha F hFS
    · -- sInf S is the greatest lower bound
      intro G hGS
      rw [le_iff]
      intro a haG
      rw [mem_sInf]
      intro F hFS
      exact le_iff.mp (hGS hFS) a haG)

theorem principal_top_eq : principal (⊤ : H) = (⊥ : HilbertFilter H) := by
  apply le_antisymm
  · -- principal(⊤) ≤ ⊥: show principal(⊤) ≤ F for every filter F.
    -- principal(⊤) = {x | ⊤ ≤ x} = {⊤}. Every filter contains ⊤.
    -- ⊥ = sInf Set.univ is the GLB of all filters.
    rw [le_iff]
    intro a ha
    rw [mem_principal] at ha
    -- ha : ⊤ ≤ a, so a = ⊤
    have ha_eq : a = ⊤ := le_antisymm le_top ha
    change a ∈ sInf (Set.univ : Set (HilbertFilter H))
    rw [mem_sInf]
    intro F _
    rw [ha_eq]
    exact F.top_mem
  · -- ⊥ ≤ principal(⊤): every a ∈ ⊥ satisfies ⊤ ≤ a.
    -- ⊥ = sInf Set.univ means a ∈ every filter, in particular a ∈ principal(⊤).
    rw [le_iff]
    intro a ha
    rw [mem_principal]
    -- ha : a ∈ ⊥ = sInf Set.univ
    have ha' : a ∈ sInf (Set.univ : Set (HilbertFilter H)) := ha
    rw [mem_sInf] at ha'
    exact ha' (principal ⊤) (Set.mem_univ _)

/-! ### Heyting implication on filters -/

/-- The Heyting implication on filters: `a ∈ (F ⇨ G)` iff the principal filter of `a`,
intersected with `F`, is contained in `G`.

Equivalently: `a ∈ (F ⇨ G) ↔ ∀ x, a ≤ x → x ∈ F → x ∈ G`.

The MP-closure proof uses the K and S axioms:
- From b ≤ x and K: x ≤ a ⇨ x (K gives `x ⇨ (a ⇨ x) = ⊤`), so `a ⇨ x ∈ F` (F is upset).
- From a ⇨ b ≤ a ⇨ x (monotonicity): apply `a ⇨ b ∈ S` to get `a ⇨ x ∈ G`.
- From x ≤ (a ⇨ x) ⇨ x (K) and S(a ⇨ x, a, x): `a ≤ (a ⇨ x) ⇨ x`.
- Apply `a ∈ S` to `(a ⇨ x) ⇨ x ∈ F`: get `(a ⇨ x) ⇨ x ∈ G`.
- Apply MP of G: `a ⇨ x ∈ G` and `(a ⇨ x) ⇨ x ∈ G` yield `x ∈ G`. ✓ -/
def himpFilter (F G : HilbertFilter H) : HilbertFilter H where
  carrier := {a | ∀ x : H, a ≤ x → x ∈ F → x ∈ G}
  top_mem x htx _ := G.upper G.top_mem htx
  upper ha hab x ha'x hxF := ha x (le_trans hab ha'x) hxF
  mp {a b} ha hab x hbx hxF := by
    -- Step 1: x ≤ a ⇨ x (K)
    have hx_le_ax : x ≤ a ⇨ x := le_himp
    -- Step 2: a ⇨ x ∈ F (F upset, x ∈ F, x ≤ a ⇨ x)
    have haxF : (a ⇨ x) ∈ F := F.upper hxF hx_le_ax
    -- Step 3: a ⇨ b ≤ a ⇨ x (monotonicity from b ≤ x)
    have hab_le : a ⇨ b ≤ a ⇨ x := himp_le_himp_left hbx
    -- Step 4: a ⇨ x ∈ G (apply hab to a ⇨ x ∈ F with a ⇨ b ≤ a ⇨ x)
    have haxG : (a ⇨ x) ∈ G := hab (a ⇨ x) hab_le haxF
    -- Step 5: x ≤ (a ⇨ x) ⇨ x (K: x ⇨ ((a ⇨ x) ⇨ x) = ⊤)
    have hx_le_axx : x ≤ (a ⇨ x) ⇨ x := le_himp
    -- Step 6: (a ⇨ x) ⇨ x ∈ F (F upset, x ∈ F, x ≤ (a ⇨ x) ⇨ x)
    have haxxF : ((a ⇨ x) ⇨ x) ∈ F := F.upper hxF hx_le_axx
    -- Step 7: a ≤ (a ⇨ x) ⇨ a (K: a ⇨ ((a ⇨ x) ⇨ a) = ⊤)
    have ha_le_axa : a ≤ (a ⇨ x) ⇨ a := le_himp
    -- Step 8: (a ⇨ x) ⇨ a ≤ (a ⇨ x) ⇨ x (S applied to (a ⇨ x, a, x))
    -- S(a ⇨ x, a, x): ((a ⇨ x) ⇨ (a ⇨ x)) ⇨ (((a ⇨ x) ⇨ a) ⇨ ((a ⇨ x) ⇨ x)) = ⊤
    -- Since (a ⇨ x) ⇨ (a ⇨ x) = ⊤: ⊤ ⇨ (((a ⇨ x) ⇨ a) ⇨ ((a ⇨ x) ⇨ x)) = ⊤
    -- top_himp: ((a ⇨ x) ⇨ a) ⇨ ((a ⇨ x) ⇨ x) = ⊤
    have haxa_le_axx : (a ⇨ x) ⇨ a ≤ (a ⇨ x) ⇨ x := by
      have hS := himp_S (a ⇨ x) a x
      simp only [himp_self, top_himp] at hS
      exact hS
    -- Step 9: a ≤ (a ⇨ x) ⇨ x (transitivity: a ≤ (a ⇨ x) ⇨ a ≤ (a ⇨ x) ⇨ x)
    have ha_le_axx : a ≤ (a ⇨ x) ⇨ x := le_trans ha_le_axa haxa_le_axx
    -- Step 10: (a ⇨ x) ⇨ x ∈ G (apply ha with a ≤ (a ⇨ x) ⇨ x and (a ⇨ x) ⇨ x ∈ F)
    have haxxG : ((a ⇨ x) ⇨ x) ∈ G := ha ((a ⇨ x) ⇨ x) ha_le_axx haxxF
    -- Step 11: x ∈ G by MP of G: a ⇨ x ∈ G and (a ⇨ x) ⇨ x ∈ G
    exact G.mp haxG haxxG

@[simp]
theorem mem_himpFilter {F G : HilbertFilter H} {a : H} :
    a ∈ himpFilter F G ↔ ∀ x : H, a ≤ x → x ∈ F → x ∈ G :=
  Set.mem_ofPred

/-- The filter lattice of a Hilbert algebra is a `GeneralizedHeytingAlgebra`.

References: [Rasiowa1974], Theorem V.3.3.

The adjunction `K ≤ F ⇨ G ↔ K ⊓ F ≤ G` holds because:
- Forward: if `K ≤ himpFilter F G` and `a ∈ K ⊓ F`, then from `a ∈ K` we get
  `∀ x ≥ a, x ∈ F → x ∈ G`; applying with `x = a` gives `a ∈ G`.
- Backward: if `K ⊓ F ≤ G` and `a ∈ K` and `x ≥ a` and `x ∈ F`, then
  `x ∈ K` (K is an upset) so `x ∈ K ⊓ F ≤ G`. -/
-- Helper: membership in the inf (complete lattice version) unfolds to membership in both factors
private theorem mem_inf_iff {F G : HilbertFilter H} {a : H} :
    a ∈ F ⊓ G ↔ a ∈ F ∧ a ∈ G := by
  change a ∈ sInf ({F, G} : Set (HilbertFilter H)) ↔ _
  rw [mem_sInf]
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · intro h; exact ⟨h F (Or.inl rfl), h G (Or.inr rfl)⟩
  · intro ⟨hF, hG⟩ K hK
    rcases hK with rfl | rfl
    · exact hF
    · exact hG

/-- The filter lattice of a Hilbert algebra is a `GeneralizedHeytingAlgebra`.

References: [Rasiowa1974], Theorem V.3.3.

The adjunction `K ≤ F ⇨ G ↔ K ⊓ F ≤ G` holds because:
- Forward: if `K ≤ himpFilter F G` and `a ∈ K ⊓ F`, then from `a ∈ K` we get
  `∀ x ≥ a, x ∈ F → x ∈ G`; applying with `x = a` gives `a ∈ G`.
- Backward: if `K ⊓ F ≤ G` and `a ∈ K` and `x ≥ a` and `x ∈ F`, then
  `x ∈ K` (K is an upset) so `x ∈ K ⊓ F ≤ G`. -/
instance instGeneralizedHeytingAlgebra : GeneralizedHeytingAlgebra (HilbertFilter H) where
  himp := himpFilter
  le_himp_iff {K F G} := by
    rw [le_iff, le_iff]
    constructor
    · intro hK a haKF
      have ⟨haK, haF⟩ := mem_inf_iff.mp haKF
      exact mem_himpFilter.mp (hK a haK) a le_rfl haF
    · intro hKF a haK
      rw [mem_himpFilter]
      intro x hax hxF
      exact hKF x (mem_inf_iff.mpr ⟨K.upper haK hax, hxF⟩)

/-! ## Phase 3: Properties of the principal filter map -/

/-- The principal filter map preserves the Heyting inequality:
`principal (a ⇨ b) ≤ himpFilter (principal a) (principal b)`.

This is the "forward half" of an algebra morphism: for `IsImpTopOnly` formulas, the
evaluation commutes with principal in the ≤ direction.

Proof: Take x ∈ principal(a ⇨ b), i.e., a ⇨ b ≤ x. Need: ∀ y, x ≤ y → a ≤ y → b ≤ y.
From a ⇨ b ≤ x ≤ y and b ≤ a ⇨ b (K axiom: b ⇨ (a ⇨ b) = ⊤): b ≤ a ⇨ b ≤ x ≤ y. ✓ -/
theorem principal_le_himp {a b : H} :
    principal (a ⇨ b) ≤ himpFilter (principal a) (principal b) := by
  intro x hx y hxy hay
  -- hx : a ⇨ b ≤ x, hxy : x ≤ y, hay : a ≤ y
  -- b ≤ a ⇨ b (K: le_himp gives b ≤ a ⇨ b)
  exact le_trans le_himp (le_trans hx hxy)

/-- The principal filter of `⊤` is the bottom of the filter lattice.
This is an alias for `principal_top_eq` provided for convenience. -/
theorem principal_top : principal (⊤ : H) = (⊥ : HilbertFilter H) := principal_top_eq

end HilbertFilter

end HilbertAlgebra

/-! ## Phase 4: Embedding Lemma -/

namespace Cslib.Logic.PL

open Proposition HilbertAlgebra HilbertAlgebra.HilbertFilter

/-- For `IsImpTopOnly` formulas, `principal` commutes with evaluation in the ≤ direction:
`principal (HilbertEvaluate v φ) ≤ AlgEvaluate (principal ∘ v) ⊥ φ`.

The inequality (rather than equality) arises because `principal` is order-reversing in the
inclusion-order lattice, and `principal_le_himp` gives only a half-morphism property. -/
theorem principal_le_algEvaluate {Atom : Type*} {H : Type*} [HilbertAlgebra H]
    (v : Atom → H) (φ : Proposition Atom) (hφ : φ.IsImpTopOnly = true) :
    principal (HilbertEvaluate v φ) ≤
      AlgEvaluate (principal ∘ v) (⊥ : HilbertFilter H) φ := by
  induction φ with
  | atom x => simp [HilbertEvaluate, AlgEvaluate]
  | bot => simp [Proposition.IsImpTopOnly] at hφ
  | imp a b _iha ihb =>
    simp only [Proposition.IsImpTopOnly, Bool.and_eq_true] at hφ
    simp only [HilbertEvaluate_imp, AlgEvaluate_imp]
    calc principal (HilbertEvaluate v a ⇨ HilbertEvaluate v b)
        ≤ principal (HilbertEvaluate v b) := principal_le_iff.mpr le_himp
      _ ≤ AlgEvaluate (principal ∘ v) ⊥ b := ihb hφ.2
      _ ≤ AlgEvaluate (principal ∘ v) ⊥ a ⇨ AlgEvaluate (principal ∘ v) ⊥ b := le_himp
  | and _ _ _ _ => simp [Proposition.IsImpTopOnly] at hφ
  | or _ _ _ _ => simp [Proposition.IsImpTopOnly] at hφ

/-- **Diego Embedding Theorem**: `HilbertEvaluate v φ = ⊤` iff
`principal (HilbertEvaluate v φ) = ⊥` (the principal filter of the evaluation is the
bottom of the filter lattice).

This characterizes validity in the Hilbert algebra H as validity in the filter lattice:
the evaluation equals the top iff the principal filter of the evaluation is the minimum
filter. The biconditional holds for all formulas, but it is primarily applied to
`IsImpTopOnly` formulas in the Diego embedding context, where `principal_le_algEvaluate`
provides the additional direction needed for the full conservativity argument.

References: [Rasiowa1974], Theorem V.3.6; [Diego1966]. -/
theorem hilbertEmbeddingLemma {Atom : Type*} {H : Type*} [HilbertAlgebra H]
    (v : Atom → H) (φ : Proposition Atom) :
    HilbertEvaluate v φ = ⊤ ↔ principal (HilbertEvaluate v φ) = (⊥ : HilbertFilter H) := by
  constructor
  · intro h
    rw [h]
    exact principal_top
  · intro h
    apply principal_injective
    rw [h, principal_top]

end Cslib.Logic.PL
