#!/usr/bin/env bash
# check-lint-suppressions.sh — ratchet gate on blanket (file-scoped) linter suppressions.
#
# THE PROBLEM THIS EXISTS TO STOP
#
# A file-scoped `set_option linter.X false` (one with no trailing `in`) silences every
# violation in the file, including every FUTURE one. Coverage accumulates rather than
# decaying: once a file carries a blanket suppression, all code later added to it is
# unlinted by construction. A survey of this tree found 14 of 14 sampled files were created
# with their blanket suppression already in the first commit -- these are not debt that crept
# in, they are the authoring habit. Ordinary tech debt gets noisier as you add code; this
# gets quieter, which is why it never surfaced on its own.
#
# THE RULE
#
#   Blanket:            set_option linter.X false          <- gated here, may only decrease
#   Declaration-scoped: set_option linter.X false in       <- always allowed
#
# Declaration-scoped suppressions are fine: they decay naturally, because they die with the
# declaration they annotate and cannot silence anything written later. Only the blanket form
# is a ratchet, so only the blanket form is counted.
#
# HOW THE GATE WORKS
#
# `lint-suppression-baseline.txt` records a per-file allowance. The check fails when a file
# exceeds its allowance, or when a file with no allowance introduces one. Counts may only go
# DOWN -- a reduction is reported and never fails. After reducing suppressions, re-baseline
# with `--update` and commit the result, which locks in the gain.
#
# Usage:
#   check-lint-suppressions.sh            verify against the baseline (exit 1 on regression)
#   check-lint-suppressions.sh --update   rewrite the baseline from the current tree
#   check-lint-suppressions.sh --list     print current per-file counts, highest first
#
# Exit: 0 clean or improved, 1 regression, 2 usage/environment error.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 2

SCAN_ROOT="Cslib"
BASELINE="scripts/lint-suppression-baseline.txt"

# A blanket suppression: `set_option linter.<name> false` with nothing after it but optional
# whitespace or a trailing `--` comment. The `$` anchor after `false` is what excludes the
# declaration-scoped `... false in` form -- do not relax it to a substring match.
BLANKET_RE='^[[:space:]]*set_option[[:space:]]+linter\.[A-Za-z0-9_.]+[[:space:]]+false[[:space:]]*(--.*)?$'

count_file() {
  # grep -c exits 1 on zero matches, so `|| echo 0` would emit two lines; assign then default.
  local n
  n=$(grep -cE "$BLANKET_RE" "$1" 2>/dev/null) || n=0
  printf '%s' "$n"
}

current_counts() {
  # Emits "<count> <path>" for every file with at least one blanket suppression, path-sorted
  # so the baseline file has a stable diff.
  local f n
  while IFS= read -r f; do
    n=$(count_file "$f")
    [ "$n" -gt 0 ] && printf '%s %s\n' "$n" "$f"
  done < <(find "$SCAN_ROOT" -name '*.lean' -type f | sort)
}

case "${1:-}" in
  --list)
    current_counts | sort -rn
    exit 0
    ;;
  --update)
    {
      echo "# Blanket (file-scoped) linter suppressions, per file. Generated by"
      echo "# scripts/check-lint-suppressions.sh --update -- do not hand-edit."
      echo "#"
      echo "# These counts are a CEILING and may only decrease. Reduce a file's suppressions"
      echo "# by narrowing them to declaration scope (\`set_option linter.X false in\`) or by"
      echo "# fixing the underlying warning, then re-run --update and commit."
      echo "#"
      echo "# Format: <count> <path>"
      current_counts
    } > "$BASELINE"
    total=$(current_counts | awk '{s+=$1} END {print s+0}')
    files=$(current_counts | wc -l | tr -d ' ')
    echo "Baseline updated: $total blanket suppressions across $files files."
    exit 0
    ;;
  "") : ;;
  *)
    echo "Usage: $0 [--update|--list]" >&2
    exit 2
    ;;
esac

if [ ! -f "$BASELINE" ]; then
  echo "FAIL: baseline $BASELINE is missing. Generate it with:" >&2
  echo "  bash $0 --update" >&2
  exit 2
fi

# Load baseline into an associative array.
declare -A allow
while read -r cnt path; do
  case "$cnt" in ''|\#*) continue ;; esac
  allow["$path"]="$cnt"
done < "$BASELINE"

regressions=0
improvements=0
new_files=0
cur_total=0

while read -r n f; do
  cur_total=$((cur_total + n))
  base="${allow[$f]:-0}"
  if [ "$n" -gt "$base" ]; then
    if [ "$base" -eq 0 ]; then
      echo "FAIL  $f"
      echo "      introduces $n blanket suppression(s); this file had none."
      new_files=$((new_files + 1))
    else
      echo "FAIL  $f"
      echo "      $n blanket suppression(s), baseline allows $base."
    fi
    regressions=$((regressions + 1))
  elif [ "$n" -lt "$base" ]; then
    improvements=$((improvements + 1))
  fi
done < <(current_counts)

base_total=$(grep -vE '^[[:space:]]*#' "$BASELINE" | awk '{s+=$1} END {print s+0}')

echo "blanket suppressions: $cur_total (baseline ceiling $base_total)"
[ "$improvements" -gt 0 ] && echo "  $improvements file(s) improved -- re-baseline with: bash $0 --update"

if [ "$regressions" -gt 0 ]; then
  cat >&2 <<EOF

FAILED: $regressions file(s) exceed their blanket-suppression allowance${new_files:+ ($new_files newly suppressed)}.

Blanket suppressions silence future violations in the whole file, so they may only
decrease. Fix by scoping the suppression to the declaration that needs it:

  set_option linter.unusedSectionVars false in
  theorem foo ...

Two traps this tree has already hit, both caught only by rebuilding:
  - \`omit [X] in\` is NOT interchangeable with \`set_option linter.X false in\`; it removes
    the instance from scope and changes the declaration's elaborated type.
  - \`set_option ... in\` must precede a declaration's doc comment, not sit between the doc
    comment and the declaration, or the file fails to parse.

If a suppression is genuinely justified at file scope, raise the baseline deliberately in
the same commit and say why in the commit message -- never as a silent side effect.
EOF
  exit 1
fi

echo "OK: no new blanket linter suppressions."
exit 0
